//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ------------------------ Structures ------------------------

struct FWPM_ACTION0_ {
    int32_t e0;
    int64_t e1;
};

struct FWPM_DISPLAY_DATA0_ {
    int16_t * e0;
    int16_t * e1;
};

struct FWPS_ACTION0_ {
    int32_t e0;
    int32_t e1;
};

struct FWPS_CLASSIFY_OUT0_ {
    int32_t e0;
    int64_t e1;
    int64_t e2;
    int32_t e3;
    int32_t e4;
    int32_t e5;
};

struct FWPS_DISCARD_METADATA0_ {
    int64_t e0;
    int32_t e1;
    int64_t e2;
};

struct FWPS_INBOUND_FRAGMENT_METADATA0_ {
    int32_t e0;
    int16_t e1;
    int32_t e2;
};

struct FWPS_INCOMING_VALUES0_ {
    int16_t e0;
    int32_t e1;
    struct FWPS_INCOMING_VALUE0_ * e2;
};

struct FWP_BYTE_BLOB_ {
    int32_t e0;
    char * e1;
};

struct FWP_CONDITION_VALUE0_ {
    int64_t e0;
    int64_t e1;
};

struct FWPS_FILTER_CONDITION0_ {
    int16_t e0;
    int16_t e1;
    int64_t e2;
    struct FWP_CONDITION_VALUE0_ e3;
};

struct FWP_VALUE0_ {
    int64_t e0;
    int64_t e1;
};

struct FWPS_FILTER1_ {
    int64_t e0;
    struct FWP_VALUE0_ e1;
    int16_t e2;
    int16_t e3;
    int32_t e4;
    struct FWPS_FILTER_CONDITION0_ * e5;
    struct FWPS_ACTION0_ e6;
    int64_t e7;
    struct FWPM_PROVIDER_CONTEXT1_ * e8;
};

struct FWPS_INCOMING_VALUE0_ {
    struct FWP_VALUE0_ e0;
};

struct _EPROCESS {
    int32_t e0;
};

struct _IP_ADDRESS_PREFIX {
    int64_t e0;
    char e1;
};

struct _KSPIN_LOCK_QUEUE {
    struct _KSPIN_LOCK_QUEUE * e0;
    int32_t * e1;
};

struct _KLOCK_QUEUE_HANDLE {
    struct _KSPIN_LOCK_QUEUE e0;
    char e1;
};

struct _KSPIN_LOCK_QUEUE {
    struct _KSPIN_LOCK_QUEUE * e0;
    int32_t * e1;
};

struct _LARGE_INTEGER {
    int64_t e0;
};

struct _MDL {
    struct _MDL * e0;
    int16_t e1;
    int16_t e2;
    int16_t e3;
    int16_t e4;
    struct _EPROCESS * e5;
    int64_t * e6;
    int64_t * e7;
    int32_t e8;
    int32_t e9;
};

struct _NDIS_OBJECT_HEADER {
    char e0;
    char e1;
    int16_t e2;
};

struct _NDIS_GENERIC_OBJECT {
    struct _NDIS_OBJECT_HEADER e0;
    int64_t * e1;
    int64_t * e2;
    int64_t e3;
};

struct _NET_BUFFER {
    int64_t e0;
    int16_t e1;
    int16_t e2;
    int64_t * e3;
    int64_t * e4[2];
    int64_t * e5[6];
    int64_t * e6[4];
    struct _LARGE_INTEGER e7;
    int64_t e8;
};

struct _NET_BUFFER_LIST {
    int64_t e0;
    struct _NET_BUFFER_LIST_CONTEXT * e1;
    struct _NET_BUFFER_LIST * e2;
    int64_t * e3;
    int64_t * e4[2];
    int64_t * e5[4];
    int64_t * e6[2];
    int64_t * e7;
    int64_t * e8;
    int32_t e9;
    int32_t e10;
    int32_t e11;
    int64_t e12;
    int64_t * e13[1];
};

struct _NET_BUFFER_LIST_CONTEXT {
    int64_t e0;
    int16_t e1;
    int16_t e2;
    char e3[1];
};

struct _NET_BUFFER_LIST_POOL_PARAMETERS {
    struct _NDIS_OBJECT_HEADER e0;
    char e1;
    char e2;
    int16_t e3;
    int32_t e4;
    int32_t e5;
};

struct _OSVERSIONINFOW {
    int32_t e0;
    int32_t e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    int16_t e5[128];
};

struct _SEC_WINNT_AUTH_IDENTITY_W {
    int16_t * e0;
    int32_t e1;
    int16_t * e2;
    int32_t e3;
    int16_t * e4;
    int32_t e5;
    int32_t e6;
};

struct _SID_IDENTIFIER_AUTHORITY {
    char e0[6];
};

struct _SID {
    char e0;
    char e1;
    struct _SID_IDENTIFIER_AUTHORITY e2;
    int32_t e3[1];
};

struct _TYPEDEF_GUID {
    int32_t e0;
    int16_t e1;
    int16_t e2;
    char e3[8];
};

struct FWPM_CALLOUT0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    struct _TYPEDEF_GUID e5;
    int32_t e6;
};

struct FWPM_FILTER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    struct _TYPEDEF_GUID e5;
    struct _TYPEDEF_GUID e6;
    struct FWP_VALUE0_ e7;
    int32_t e8;
    struct FWPM_FILTER_CONDITION0_ * e9;
    struct FWPM_ACTION0_ e10;
    int64_t e11;
    struct _TYPEDEF_GUID * e12;
    int64_t e13;
    struct FWP_VALUE0_ e14;
};

struct FWPM_FILTER_CONDITION0_ {
    struct _TYPEDEF_GUID e0;
    int64_t e1;
    struct FWP_CONDITION_VALUE0_ e2;
};

struct FWPM_PROVIDER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct FWP_BYTE_BLOB_ e3;
    int16_t * e4;
};

struct FWPM_PROVIDER_CONTEXT1_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    int64_t e5;
    int64_t e6;
    int64_t e7;
};

struct FWPM_SESSION0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    struct _SID * e5;
    int16_t * e6;
    bool e7;
};

struct FWPM_SUBLAYER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    int16_t e5;
};

struct FWPS_CALLOUT1_ {
    struct _TYPEDEF_GUID e0;
    int32_t e1;
    void (*e2)(struct FWPS_INCOMING_VALUES0_ *, struct FWPS_INCOMING_METADATA_VALUES0_ *, int64_t *, int64_t *, struct FWPS_FILTER1_ *, int64_t, struct FWPS_CLASSIFY_OUT0_ *);
    int32_t (*e3)(int64_t, struct _TYPEDEF_GUID *, struct FWPS_FILTER1_ *);
    void (*e4)(int16_t, int32_t, int64_t);
};

struct _TYPEDEF_SCOPE_ID__PSCOPE_ID {
    int64_t e0;
};

struct FWPS_INCOMING_METADATA_VALUES0_ {
    int32_t e0;
    int32_t e1;
    int64_t e2;
    struct FWPS_DISCARD_METADATA0_ e3;
    int64_t e4;
    int32_t e5;
    int32_t e6;
    struct FWP_BYTE_BLOB_ * e7;
    int64_t e8;
    int64_t e9;
    int32_t e10;
    int32_t e11;
    int32_t e12;
    struct FWPS_INBOUND_FRAGMENT_METADATA0_ e13;
    int32_t e14;
    int64_t * e15;
    int64_t e16;
    struct _TYPEDEF_SCOPE_ID__PSCOPE_ID e17;
    struct _WSACMSGHDR * e18;
    int32_t e19;
    int64_t e20;
    int64_t * e21;
    int32_t e22;
    struct _IP_ADDRESS_PREFIX e23;
    int16_t e24;
    int64_t e25;
    int32_t e26;
    int32_t e27;
    struct sockaddr * e28;
    int64_t * e29;
    int32_t e30;
    int32_t e31;
    int32_t e32;
    int32_t e33;
    int32_t e34;
    int16_t e35;
    int32_t e36;
    int64_t * e37;
    int64_t * e38;
    int64_t e39;
};

struct FWPS_TRANSPORT_SEND_PARAMS0_ {
    char * e0;
    struct _TYPEDEF_SCOPE_ID__PSCOPE_ID e1;
    int64_t * e2;
    int32_t e3;
};

struct _UNICODE_STRING {
    int16_t e0;
    int16_t e1;
    int16_t * e2;
};

struct _WSACMSGHDR {
    int32_t e0;
    int32_t e1;
    int32_t e2;
};

struct sockaddr {
    int16_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(int64_t a1, int64_t a2);
/* Extracted from ProxifierDrv.sys (RetDec). WFP hooks subset. */

int64_t function_140018000(void) {
    // 0x140018000
    int64_t result; // 0x140018000
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: microsoft
// Detected functions: 139


int64_t function_140003c64(int64_t a1, int64_t a2) {
    int64_t v1 = *(int64_t *)((int64_t)g14 + 64); // 0x140003cb5
    function_14000199c(v1, a2 & -256 | 4, 1, 10, (int64_t)&g10);
    function_1400016cc();
    int32_t v2 = FwpsRedirectHandleCreate0((struct _TYPEDEF_GUID *)&g7, 0, (int64_t **)&g51); // 0x140003cd7
    if (v2 < 0) {
        // 0x140003cec
        function_140001988((char *)(int64_t)"42:FwpsRedirectHandleCreate0 failed", (int64_t)v2, 0, 10);
        // 0x14000424e
        return function_1400055d0(g16);
    }
    int64_t v3 = function_140002c68(); // 0x140003cfb
    int64_t v4 = v3; // 0x140003d04
    int64_t v5 = (int64_t)"50:CalloutRedirectInitialize failed"; // 0x140003d04
    int32_t v6; // 0x140003c64
    int64_t v7; // 0x140003c64
    int64_t v8; // 0x140003c64
    int64_t v9; // 0x140003c64
    int64_t v10; // 0x140003c64
    int64_t v11; // 0x140003c64
    int64_t v12; // 0x140003c64
    int64_t v13; // 0x140003c64
    int64_t v14; // 0x140003c64
    if ((int32_t)v3 >= 0) {
        // 0x140003d1c
        v4 = function_140002678();
        v5 = (int64_t)"57:CalloutFlowInitialize failed";
        if ((int32_t)v4 >= 0) {
            int32_t v15 = FwpsInjectionHandleCreate0(0, 2, (int64_t **)&g52); // 0x140003d3c
            if (v15 < 0) {
                // 0x140003cec
                function_140001988((char *)(int64_t)"64:FwpsInjectionHandleCreate failed(FWPS_INJECTION_TYPE_TRANSPORT)", (int64_t)v15, 0, 10);
                // 0x14000424e
                return function_1400055d0(g16);
            }
            int32_t v16 = FwpsInjectionHandleCreate0(0, 1, (int64_t **)&g53); // 0x140003d5c
            int64_t v17 = v16; // 0x140003d61
            if (v16 < 0) {
                // 0x140003cec
                function_140001988((char *)(int64_t)"71:FwpsInjectionHandleCreate failed(FWPS_INJECTION_TYPE_STREAM)", v17, 0, 10);
                // 0x14000424e
                return function_1400055d0(g16);
            }
            struct _NDIS_GENERIC_OBJECT * v18 = NdisAllocateGenericObject(a2, 0x624f644e, 0); // 0x140003d7e
            g54 = v18;
            v10 = (int64_t)"78:NdisAllocateGenericObject failed";
            v12 = 0xc0000017;
            v8 = v17;
            if (v18 != NULL) {
                int64_t v19 = 0x100180; // bp-296, 0x140003db4
                int64_t * v20 = NdisAllocateNetBufferListPool((int64_t *)v18, (struct _NET_BUFFER_LIST_POOL_PARAMETERS *)&v19); // 0x140003dc9
                g55 = (int64_t)v20;
                v10 = (int64_t)"96:NdisAllocateNetBufferListPool failed";
                v12 = 0xc0000017;
                v8 = v17;
                if (v20 != NULL) {
                    // 0x140003deb
                    int32_t v21; // bp-200, 0x140003c64
                    int64_t v22; // bp-664, 0x140003c64
                    if (*(int64_t *)0x140008010 != 0) {
                        int64_t v23 = &v21;
                        int64_t v24 = 0; // 0x140003e9c
                        int64_t v25 = 0;
                        int64_t v26 = 0;
                        int64_t v27; // 0x140003e25
                        int128_t v28; // 0x140003e38
                        int32_t v29; // 0x140003e7d
                        int64_t v30; // 0x140003f2b
                        int64_t v31; // 0x140003e8c
                        if (*(int64_t *)(v26 + (int64_t)&g15 + 24) != 0) {
                            // 0x140003e13
                            function_140005d00(v23, 0, 48);
                            v27 = *(int64_t *)(v26 + (int64_t)&g15);
                            v28 = __asm_movups(*(int128_t *)v27);
                            v22 = 0;
                            v21 = __asm_movdqu(v28);
                            v29 = FwpsCalloutRegister1((int64_t *)a1, (struct FWPS_CALLOUT1_ *)&v21, (int32_t *)&v22);
                            if (v29 < 0) {
                                // 0x140003f1b
                                v30 = *(int64_t *)(56 * (0x100000000 * v25 >> 32) + (int64_t)&g15);
                                v11 = (int64_t)"117:FwpsCalloutRegister1 failed";
                                v13 = v29;
                                v6 = *(int32_t *)v30;
                                v7 = 10;
                                goto lab_0x1400041f5;
                            }
                            // 0x140003e8c
                            v31 = *(int64_t *)(v26 + (int64_t)&g15 + 40);
                            if (v31 != 0) {
                                // 0x140003e96
                                *(int32_t *)v31 = (int32_t)v22;
                            }
                        }
                        // 0x140003e9c
                        v24++;
                        int64_t v32 = 56 * v24; // 0x140003ea2
                        int64_t v33 = v25 + 1 & 0xffffffff; // 0x140003eaa
                        while (*(int64_t *)(v32 + (int64_t)&g15) != 0) {
                            // 0x140003e08
                            v25 = v33;
                            v26 = v32;
                            if (*(int64_t *)(v26 + (int64_t)&g15 + 24) != 0) {
                                // 0x140003e13
                                function_140005d00(v23, 0, 48);
                                v27 = *(int64_t *)(v26 + (int64_t)&g15);
                                v28 = __asm_movups(*(int128_t *)v27);
                                v22 = 0;
                                v21 = __asm_movdqu(v28);
                                v29 = FwpsCalloutRegister1((int64_t *)a1, (struct FWPS_CALLOUT1_ *)&v21, (int32_t *)&v22);
                                if (v29 < 0) {
                                    // 0x140003f1b
                                    v30 = *(int64_t *)(56 * (0x100000000 * v25 >> 32) + (int64_t)&g15);
                                    v11 = (int64_t)"117:FwpsCalloutRegister1 failed";
                                    v13 = v29;
                                    v6 = *(int32_t *)v30;
                                    v7 = 10;
                                    goto lab_0x1400041f5;
                                }
                                // 0x140003e8c
                                v31 = *(int64_t *)(v26 + (int64_t)&g15 + 40);
                                if (v31 != 0) {
                                    // 0x140003e96
                                    *(int32_t *)v31 = (int32_t)v22;
                                }
                            }
                            // 0x140003e9c
                            v24++;
                            v32 = 56 * v24;
                            v33 = v25 + 1 & 0xffffffff;
                        }
                    }
                    // 0x140003eb0
                    int64_t v34; // bp-280, 0x140003c64
                    int64_t v35 = &v34; // 0x140003eb5
                    function_140005d00(v35, 0, 72);
                    int64_t v36 = 0; // bp-656, 0x140003ee4
                    int32_t v37 = FwpmEngineOpen0(NULL, 10, NULL, (struct FWPM_SESSION0_ *)&v34, (int64_t **)&v36); // 0x140003eee
                    g60 = v36;
                    if (v37 >= 0) {
                        // 0x140003f37
                        int64_t v38; // bp-568, 0x140003c64
                        function_140005d00((int64_t)&v38, 0, 64);
                        v38 = __asm_movdqu(__asm_movups(0x45a51aef387a42c3));
                        int32_t v39 = FwpmProviderAdd0((int64_t *)v36, (struct FWPM_PROVIDER0_ *)&v38, NULL); // 0x140003f6b
                        if (v39 >= 0) {
                            // 0x140003f85
                            int32_t v40; // bp-648, 0x140003c64
                            int64_t v41 = &v40; // 0x140003f88
                            function_140005d00(v41, 0, 72);
                            v40 = __asm_movdqu(__asm_movups(g8));
                            int32_t v42 = FwpmSubLayerAdd0((int64_t *)g60, (struct FWPM_SUBLAYER0_ *)&v40, NULL); // 0x140003fdb
                            int64_t v43 = v42;
                            if (v42 >= 0) {
                                // 0x140003ff7
                                v14 = v41;
                                v9 = v43;
                                if (g15 == 0) {
                                    goto lab_0x140004201_2;
                                } else {
                                    int64_t v44 = &v21;
                                    int64_t v45 = 0; // 0x14000407d
                                    int64_t v46 = 0;
                                    int64_t v47 = v41; // 0x140004012
                                    int64_t v48 = v43; // 0x140004012
                                    int64_t v49; // 0x140004026
                                    int128_t v50; // 0x14000403e
                                    int64_t v51; // 0x140004041
                                    int32_t v52; // 0x14000406e
                                    int64_t v53; // 0x140003c64
                                    if (*(int64_t *)(v46 + (int64_t)&g15 + 24) != 0) {
                                        // 0x140004014
                                        function_140005d00(v44, 0, 88);
                                        v49 = *(int64_t *)(v46 + (int64_t)&g15);
                                        v50 = __asm_movups(*(int128_t *)v49);
                                        v51 = *(int64_t *)(v46 + (int64_t)&g15 + 8);
                                        v21 = __asm_movdqu(v50);
                                        __asm_movdqu(__asm_movups(*(int128_t *)v51));
                                        v52 = FwpmCalloutAdd0((int64_t *)g60, (struct FWPM_CALLOUT0_ *)&v21, NULL, NULL);
                                        v53 = v52;
                                        v47 = v44;
                                        v48 = v53;
                                        if (v52 < 0) {
                                            // 0x1400041d8
                                            v11 = (int64_t)"182:FwpmCalloutAdd0 failed";
                                            v13 = v53;
                                            v6 = v21;
                                            v7 = 0;
                                            goto lab_0x1400041f5;
                                        }
                                    }
                                    int64_t v54 = v48;
                                    int64_t v55 = v47;
                                    v45++;
                                    int64_t v56 = 56 * v45; // 0x140004080
                                    while (*(int64_t *)(v56 + (int64_t)&g15) != 0) {
                                        // 0x14000400a
                                        v46 = v56;
                                        v47 = v55;
                                        v48 = v54;
                                        if (*(int64_t *)(v46 + (int64_t)&g15 + 24) != 0) {
                                            // 0x140004014
                                            function_140005d00(v44, 0, 88);
                                            v49 = *(int64_t *)(v46 + (int64_t)&g15);
                                            v50 = __asm_movups(*(int128_t *)v49);
                                            v51 = *(int64_t *)(v46 + (int64_t)&g15 + 8);
                                            v21 = __asm_movdqu(v50);
                                            __asm_movdqu(__asm_movups(*(int128_t *)v51));
                                            v52 = FwpmCalloutAdd0((int64_t *)g60, (struct FWPM_CALLOUT0_ *)&v21, NULL, NULL);
                                            v53 = v52;
                                            v47 = v44;
                                            v48 = v53;
                                            if (v52 < 0) {
                                                // 0x1400041d8
                                                v11 = (int64_t)"182:FwpmCalloutAdd0 failed";
                                                v13 = v53;
                                                v6 = v21;
                                                v7 = 0;
                                                goto lab_0x1400041f5;
                                            }
                                        }
                                        // 0x14000407d
                                        v54 = v48;
                                        v55 = v47;
                                        v45++;
                                        v56 = 56 * v45;
                                    }
                                    // 0x14000408a
                                    v14 = v55;
                                    v9 = v54;
                                    if (g15 == 0) {
                                        goto lab_0x140004201_2;
                                    } else {
                                        // 0x1400040a0
                                        int64_t v57; // bp-504, 0x140003c64
                                        int64_t v58 = &v57;
                                        int64_t v59 = 0; // 0x1400041c2
                                        int64_t v60 = 0; // 0x1400041c5
                                        int64_t v61 = &g15; // 0x1400041c9
                                        function_140005d00(v44, 0, 120);
                                        int64_t v62 = 0; // 0x1400040bf
                                        if (*(char *)(v60 + (int64_t)&g15 + 16) != 0) {
                                            // 0x1400040c1
                                            v21 = __asm_movdqu(__asm_movups(g11));
                                            v62 = 40;
                                        }
                                        uint32_t v63 = *(int32_t *)(v60 + (int64_t)&g15 + 20); // 0x1400040ef
                                        int64_t v64; // bp-456, 0x140003c64
                                        int128_t v65; // 0x1400040f8
                                        int64_t v66; // 0x140003c64
                                        if (v63 != 0) {
                                            // 0x1400040f8
                                            v65 = __asm_movups(g12);
                                            v66 = v62 + (int64_t)&v64;
                                            *(int32_t *)(v66 + 280) = 2;
                                            *(int16_t *)(v66 + 288) = (int16_t)v63;
                                            *(int128_t *)(v66 + 256) = (int128_t)__asm_movdqu(v65);
                                            *(int32_t *)(v66 + 272) = v63 > 0x10000 ? 10 : 0;
                                        }
                                        // 0x140004139
                                        function_140005d00(v58, 0, 200);
                                        int64_t v67 = *(int64_t *)(v60 + (int64_t)&g15 + 8); // 0x14000414a
                                        int128_t v68 = __asm_movups(g8); // 0x140004154
                                        int128_t v69 = __asm_movups(*(int128_t *)v67); // 0x140004169
                                        __asm_movdqu(v68);
                                        __asm_movdqu(v69);
                                        int64_t v70 = __asm_movdqu(__asm_movups(*(int128_t *)*(int64_t *)v61)); // 0x1400041aa
                                        v22 = 0;
                                        uint32_t v71 = FwpmFilterAdd0((int64_t *)g60, (struct FWPM_FILTER0_ *)&v57, NULL, &v22); // 0x1400041b7
                                        while (v71 >= 0) {
                                            // 0x1400041c2
                                            v59++;
                                            v60 = 56 * v59;
                                            v61 = v60 + (int64_t)&g15;
                                            if (*(int64_t *)v61 == 0) {
                                                // 0x140004201
                                                v14 = v58;
                                                v9 = v71;
                                                goto lab_0x140004201_2;
                                            }
                                            function_140005d00(v44, 0, 120);
                                            v62 = 0;
                                            if (*(char *)(v60 + (int64_t)&g15 + 16) != 0) {
                                                // 0x1400040c1
                                                v21 = __asm_movdqu(__asm_movups(g11));
                                                v62 = 40;
                                            }
                                            // 0x1400040ef
                                            v63 = *(int32_t *)(v60 + (int64_t)&g15 + 20);
                                            if (v63 != 0) {
                                                // 0x1400040f8
                                                v65 = __asm_movups(g12);
                                                v66 = v62 + (int64_t)&v64;
                                                *(int32_t *)(v66 + 280) = 2;
                                                *(int16_t *)(v66 + 288) = (int16_t)v63;
                                                *(int128_t *)(v66 + 256) = (int128_t)__asm_movdqu(v65);
                                                *(int32_t *)(v66 + 272) = v63 > 0x10000 ? 10 : 0;
                                            }
                                            // 0x140004139
                                            function_140005d00(v58, 0, 200);
                                            v67 = *(int64_t *)(v60 + (int64_t)&g15 + 8);
                                            v68 = __asm_movups(g8);
                                            v69 = __asm_movups(*(int128_t *)v67);
                                            __asm_movdqu(v68);
                                            __asm_movdqu(v69);
                                            v70 = __asm_movdqu(__asm_movups(*(int128_t *)*(int64_t *)v61));
                                            v22 = 0;
                                            v71 = FwpmFilterAdd0((int64_t *)g60, (struct FWPM_FILTER0_ *)&v57, NULL, &v22);
                                        }
                                        // 0x1400041e8
                                        v11 = (int64_t)"241:FwpmFilterAdd0 failed";
                                        v13 = v71;
                                        v6 = v70;
                                        v7 = &v22;
                                        goto lab_0x1400041f5;
                                    }
                                }
                            } else {
                                // 0x140003fe6
                                v11 = (int64_t)"163:FwpmSubLayerAdd failed";
                                v13 = v43;
                                v6 = v40;
                                v7 = v35;
                                goto lab_0x1400041f5;
                            }
                        } else {
                            // 0x140003f76
                            v11 = (int64_t)"147:FwpmProviderAdd0 failed";
                            v13 = v39;
                            v6 = 0;
                            v7 = v35;
                            goto lab_0x1400041f5;
                        }
                    } else {
                        // 0x140003f05
                        g60 = 0;
                        v11 = (int64_t)"135:FwpmEngineOpen0 failed";
                        v13 = v37;
                        v6 = 0;
                        v7 = v35;
                        goto lab_0x1400041f5;
                    }
                } else {
                    goto lab_0x140003d0f;
                }
            } else {
                goto lab_0x140003d0f;
            }
        } else {
            goto lab_0x140003d0d;
        }
    } else {
        goto lab_0x140003d0d;
    }
  lab_0x140003d0d:;
    int64_t v72 = v4 & 0xffffffff;
    v10 = v5;
    v12 = v72;
    v8 = v72;
    goto lab_0x140003d0f;
  lab_0x140003d0f:
    // 0x140003d0f
    function_140001988((char *)v10, v12, 0, 10);
    v14 = v12;
    v9 = v8;
    goto lab_0x140004201_2;
  lab_0x140004201_2:;
    int64_t v73 = g14;
    int64_t v74 = v14 & -256;
    if ((int32_t)v9 >= 0) {
        int64_t v75 = *(int64_t *)(v73 + 64); // 0x140004241
        function_14000199c(v75, v74 | 4, 1, 12, (int64_t)&g10);
    } else {
        int64_t v76 = v74 | 2; // 0x140004212
        int64_t v77 = *(int64_t *)(v73 + 64); // 0x140004219
        function_14000199c(v77, v76, 1, 11, (int64_t)&g10);
        function_14000427c(v77, v76);
    }
    // 0x14000424e
    return function_1400055d0(g16);
  lab_0x1400041f5:
    // 0x1400041f5
    function_140001988((char *)v11, v13, v6, v7);
    v14 = v13;
    v9 = v13;
    goto lab_0x140004201_2;
}

// Address range: 0x14000427c - 0x140004400
int64_t function_14000427c(int64_t a1, int64_t a2) {
    int64_t v1 = a2 & -256 | 4; // 0x1400042a9
    int64_t v2 = *(int64_t *)((int64_t)g14 + 64); // 0x1400042ab
    function_14000199c(v2, v1, 1, 13, (int64_t)&g10);
    int64_t v3 = g60; // 0x1400042b8
    g23 = 0;
    if (v3 != 0) {
        // 0x1400042cb
        FwpmEngineClose0((int64_t *)v3);
        g60 = 0;
    }
    // 0x1400042d8
    function_1400026ac(v3);
    function_140002c9c(v3);
    int64_t v4 = 0; // 0x1400042eb
    int64_t v5 = v1; // 0x1400042eb
    int64_t v6 = 0; // 0x1400042eb
    if (g15 != 0) {
        int64_t v7 = v1; // 0x140004301
        int64_t v8 = 0; // 0x140004301
        int32_t v9; // 0x140004306
        int64_t v10; // 0x14000430b
        int64_t v11; // 0x140004311
        if (*(int64_t *)(24 + (int64_t)&g15) != 0) {
            // 0x140004303
            v9 = FwpsCalloutUnregisterByKey0((struct _TYPEDEF_GUID *)g15);
            v10 = v9;
            v7 = v1;
            v8 = v10;
            if (v9 < 0) {
                // 0x140004311
                v11 = *(int64_t *)(int64_t)&g15;
                function_140001988("282:FwpsCalloutUnregisterByKey", v10, *(int32_t *)v11, 13);
                v7 = v10;
                v8 = v10;
            }
        }
        int64_t v12 = v8;
        int64_t v13 = v7;
        v4++;
        int64_t v14 = 56 * v4; // 0x140004328
        int64_t v15 = v14 + (int64_t)&g15; // 0x14000432c
        int64_t v16 = *(int64_t *)v15; // 0x140004330
        int64_t v17 = v16; // 0x140004334
        int64_t v18 = v15; // 0x140004334
        v5 = v13;
        v6 = v12;
        while (v16 != 0) {
            int64_t v19 = v13;
            v7 = v19;
            v8 = v12;
            if (*(int64_t *)(v14 + (int64_t)&g15 + 24) != 0) {
                // 0x140004303
                v9 = FwpsCalloutUnregisterByKey0((struct _TYPEDEF_GUID *)v17);
                v10 = v9;
                v7 = v19;
                v8 = v10;
                if (v9 < 0) {
                    // 0x140004311
                    v11 = *(int64_t *)v18;
                    function_140001988("282:FwpsCalloutUnregisterByKey", v10, *(int32_t *)v11, 13);
                    v7 = v10;
                    v8 = v10;
                }
            }
            // 0x140004325
            v12 = v8;
            v13 = v7;
            v4++;
            v14 = 56 * v4;
            v15 = v14 + (int64_t)&g15;
            v16 = *(int64_t *)v15;
            v17 = v16;
            v18 = v15;
            v5 = v13;
            v6 = v12;
        }
    }
    // 0x140004336
    if (g51 != 0) {
        // 0x140004342
        FwpsRedirectHandleDestroy0((int64_t *)g51);
        g51 = 0;
    }
    int64_t v20 = v5; // 0x140004359
    int64_t v21 = v6; // 0x140004359
    if (g52 != 0) {
        int32_t v22 = FwpsInjectionHandleDestroy0((int64_t *)g52); // 0x14000435b
        v21 = v22;
        v20 = v5;
        if (v22 < 0) {
            // 0x140004366
            function_140001988("297:FwpsInjectionHandleDestroy(g_InjectionTransportHandle) failed", v21, 0, 13);
            v20 = v21;
        }
        // 0x140004377
        g52 = 0;
    }
    int64_t v23 = v20; // 0x140004389
    int64_t v24 = v21; // 0x140004389
    if (g53 != 0) {
        int32_t v25 = FwpsInjectionHandleDestroy0((int64_t *)g53); // 0x14000438b
        v24 = v25;
        v23 = v20;
        if (v25 < 0) {
            // 0x140004396
            function_140001988("306:FwpsInjectionHandleDestroy(g_InjectionStreamHandle) failed", v24, 0, 13);
            v23 = v24;
        }
        // 0x1400043a7
        g53 = 0;
    }
    // 0x1400043af
    if (g55 != 0) {
        // 0x1400043bb
        NdisFreeNetBufferListPool((int64_t *)g55);
        g55 = 0;
    }
    // 0x1400043c8
    if (g54 != NULL) {
        // 0x1400043d4
        NdisFreeGenericObject(g54);
        g54 = NULL;
    }
    // 0x1400043e1
    function_140001658(0, v23);
    return v24 & 0xffffffff;
}

// Address range: 0x140004400 - 0x1400044a7
int64_t function_14000137c(void) {
    // 0x14000137c
    if (g29 == 0) {
        // 0x1400013f0
        int64_t v1; // 0x14000137c
        return v1 & -256;
    }
    uint64_t v2 = KeQueryUnbiasedInterruptTime(); // 0x140001394
    int64_t v3; // bp-40, 0x14000137c
    KeAcquireInStackQueuedSpinLock((int32_t *)&g79, (struct _KLOCK_QUEUE_HANDLE *)&v3);
    int64_t result = (int64_t)&g80 & -256; // 0x1400013c0
    if (g36 != (int64_t)&g36) {
        int64_t v4 = *(int64_t *)(g36 + 200); // 0x1400013cf
        result = (int64_t)(v2 > v4 + (int64_t)(0x989680 * g29)) | (int64_t)&g80 & -256;
    }
    // 0x1400013e3
    KeReleaseInStackQueuedSpinLock((struct _KLOCK_QUEUE_HANDLE *)&v3);
    // 0x1400013f0
    return result;
}

// Address range: 0x1400013fc - 0x140001656
int64_t function_140002678(void) {
    // 0x140002678
    g45 = (int128_t *)&g44;
    g44 = (int128_t *)&g44;
    KeInitializeSpinLock((int32_t *)&g78);
    g46 = 0;
    return (int32_t)&g80 ^ (int32_t)&g80;
}

// Address range: 0x1400026ac - 0x1400026b3
