//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ------------------------ Structures ------------------------

struct FWPM_ACTION0_ {
    int32_t e0;
    int64_t e1;
};

struct FWPM_DISPLAY_DATA0_ {
    int16_t * e0;
    int16_t * e1;
};

struct FWPS_ACTION0_ {
    int32_t e0;
    int32_t e1;
};

struct FWPS_CLASSIFY_OUT0_ {
    int32_t e0;
    int64_t e1;
    int64_t e2;
    int32_t e3;
    int32_t e4;
    int32_t e5;
};

struct FWPS_DISCARD_METADATA0_ {
    int64_t e0;
    int32_t e1;
    int64_t e2;
};

struct FWPS_INBOUND_FRAGMENT_METADATA0_ {
    int32_t e0;
    int16_t e1;
    int32_t e2;
};

struct FWPS_INCOMING_VALUES0_ {
    int16_t e0;
    int32_t e1;
    struct FWPS_INCOMING_VALUE0_ * e2;
};

struct FWP_BYTE_BLOB_ {
    int32_t e0;
    char * e1;
};

struct FWP_CONDITION_VALUE0_ {
    int64_t e0;
    int64_t e1;
};

struct FWPS_FILTER_CONDITION0_ {
    int16_t e0;
    int16_t e1;
    int64_t e2;
    struct FWP_CONDITION_VALUE0_ e3;
};

struct FWP_VALUE0_ {
    int64_t e0;
    int64_t e1;
};

struct FWPS_FILTER1_ {
    int64_t e0;
    struct FWP_VALUE0_ e1;
    int16_t e2;
    int16_t e3;
    int32_t e4;
    struct FWPS_FILTER_CONDITION0_ * e5;
    struct FWPS_ACTION0_ e6;
    int64_t e7;
    struct FWPM_PROVIDER_CONTEXT1_ * e8;
};

struct FWPS_INCOMING_VALUE0_ {
    struct FWP_VALUE0_ e0;
};

struct _EPROCESS {
    int32_t e0;
};

struct _IP_ADDRESS_PREFIX {
    int64_t e0;
    char e1;
};

struct _KSPIN_LOCK_QUEUE {
    struct _KSPIN_LOCK_QUEUE * e0;
    int32_t * e1;
};

struct _KLOCK_QUEUE_HANDLE {
    struct _KSPIN_LOCK_QUEUE e0;
    char e1;
};

struct _KSPIN_LOCK_QUEUE {
    struct _KSPIN_LOCK_QUEUE * e0;
    int32_t * e1;
};

struct _LARGE_INTEGER {
    int64_t e0;
};

struct _MDL {
    struct _MDL * e0;
    int16_t e1;
    int16_t e2;
    int16_t e3;
    int16_t e4;
    struct _EPROCESS * e5;
    int64_t * e6;
    int64_t * e7;
    int32_t e8;
    int32_t e9;
};

struct _NDIS_OBJECT_HEADER {
    char e0;
    char e1;
    int16_t e2;
};

struct _NDIS_GENERIC_OBJECT {
    struct _NDIS_OBJECT_HEADER e0;
    int64_t * e1;
    int64_t * e2;
    int64_t e3;
};

struct _NET_BUFFER {
    int64_t e0;
    int16_t e1;
    int16_t e2;
    int64_t * e3;
    int64_t * e4[2];
    int64_t * e5[6];
    int64_t * e6[4];
    struct _LARGE_INTEGER e7;
    int64_t e8;
};

struct _NET_BUFFER_LIST {
    int64_t e0;
    struct _NET_BUFFER_LIST_CONTEXT * e1;
    struct _NET_BUFFER_LIST * e2;
    int64_t * e3;
    int64_t * e4[2];
    int64_t * e5[4];
    int64_t * e6[2];
    int64_t * e7;
    int64_t * e8;
    int32_t e9;
    int32_t e10;
    int32_t e11;
    int64_t e12;
    int64_t * e13[1];
};

struct _NET_BUFFER_LIST_CONTEXT {
    int64_t e0;
    int16_t e1;
    int16_t e2;
    char e3[1];
};

struct _NET_BUFFER_LIST_POOL_PARAMETERS {
    struct _NDIS_OBJECT_HEADER e0;
    char e1;
    char e2;
    int16_t e3;
    int32_t e4;
    int32_t e5;
};

struct _OSVERSIONINFOW {
    int32_t e0;
    int32_t e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    int16_t e5[128];
};

struct _SEC_WINNT_AUTH_IDENTITY_W {
    int16_t * e0;
    int32_t e1;
    int16_t * e2;
    int32_t e3;
    int16_t * e4;
    int32_t e5;
    int32_t e6;
};

struct _SID_IDENTIFIER_AUTHORITY {
    char e0[6];
};

struct _SID {
    char e0;
    char e1;
    struct _SID_IDENTIFIER_AUTHORITY e2;
    int32_t e3[1];
};

struct _TYPEDEF_GUID {
    int32_t e0;
    int16_t e1;
    int16_t e2;
    char e3[8];
};

struct FWPM_CALLOUT0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    struct _TYPEDEF_GUID e5;
    int32_t e6;
};

struct FWPM_FILTER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    struct _TYPEDEF_GUID e5;
    struct _TYPEDEF_GUID e6;
    struct FWP_VALUE0_ e7;
    int32_t e8;
    struct FWPM_FILTER_CONDITION0_ * e9;
    struct FWPM_ACTION0_ e10;
    int64_t e11;
    struct _TYPEDEF_GUID * e12;
    int64_t e13;
    struct FWP_VALUE0_ e14;
};

struct FWPM_FILTER_CONDITION0_ {
    struct _TYPEDEF_GUID e0;
    int64_t e1;
    struct FWP_CONDITION_VALUE0_ e2;
};

struct FWPM_PROVIDER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct FWP_BYTE_BLOB_ e3;
    int16_t * e4;
};

struct FWPM_PROVIDER_CONTEXT1_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    int64_t e5;
    int64_t e6;
    int64_t e7;
};

struct FWPM_SESSION0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    struct _SID * e5;
    int16_t * e6;
    bool e7;
};

struct FWPM_SUBLAYER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    int16_t e5;
};

struct FWPS_CALLOUT1_ {
    struct _TYPEDEF_GUID e0;
    int32_t e1;
    void (*e2)(struct FWPS_INCOMING_VALUES0_ *, struct FWPS_INCOMING_METADATA_VALUES0_ *, int64_t *, int64_t *, struct FWPS_FILTER1_ *, int64_t, struct FWPS_CLASSIFY_OUT0_ *);
    int32_t (*e3)(int64_t, struct _TYPEDEF_GUID *, struct FWPS_FILTER1_ *);
    void (*e4)(int16_t, int32_t, int64_t);
};

struct _TYPEDEF_SCOPE_ID__PSCOPE_ID {
    int64_t e0;
};

struct FWPS_INCOMING_METADATA_VALUES0_ {
    int32_t e0;
    int32_t e1;
    int64_t e2;
    struct FWPS_DISCARD_METADATA0_ e3;
    int64_t e4;
    int32_t e5;
    int32_t e6;
    struct FWP_BYTE_BLOB_ * e7;
    int64_t e8;
    int64_t e9;
    int32_t e10;
    int32_t e11;
    int32_t e12;
    struct FWPS_INBOUND_FRAGMENT_METADATA0_ e13;
    int32_t e14;
    int64_t * e15;
    int64_t e16;
    struct _TYPEDEF_SCOPE_ID__PSCOPE_ID e17;
    struct _WSACMSGHDR * e18;
    int32_t e19;
    int64_t e20;
    int64_t * e21;
    int32_t e22;
    struct _IP_ADDRESS_PREFIX e23;
    int16_t e24;
    int64_t e25;
    int32_t e26;
    int32_t e27;
    struct sockaddr * e28;
    int64_t * e29;
    int32_t e30;
    int32_t e31;
    int32_t e32;
    int32_t e33;
    int32_t e34;
    int16_t e35;
    int32_t e36;
    int64_t * e37;
    int64_t * e38;
    int64_t e39;
};

struct FWPS_TRANSPORT_SEND_PARAMS0_ {
    char * e0;
    struct _TYPEDEF_SCOPE_ID__PSCOPE_ID e1;
    int64_t * e2;
    int32_t e3;
};

struct _UNICODE_STRING {
    int16_t e0;
    int16_t e1;
    int16_t * e2;
};

struct _WSACMSGHDR {
    int32_t e0;
    int32_t e1;
    int32_t e2;
};

struct sockaddr {
    int16_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(int64_t a1, int64_t a2);
/* Extracted from ProxifierDrv.sys (RetDec). WFP hooks subset. */

int64_t function_140001000(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6, int64_t a7) {
    int64_t v1 = a2 & -256; // 0x14000103c
    int64_t v2 = v1 | 5; // 0x14000103c
    int64_t v3 = *(int64_t *)(*(int64_t *)0x140008000 + 64); // 0x14000103e
    function_14000199c(v3, v2, 1, 21, (int64_t)&g2);
    uint32_t result = *(int32_t *)(a7 + 24); // 0x140001053
    if (result % 2 == 0) {
        int64_t v4 = *(int64_t *)((int64_t)g14 + 64); // 0x14000106e
        // 0x14000111a
        return function_14000199c(v4, v1 | 4, 1, 22, (int64_t)&g2);
    }
    // 0x140001080
    *(int32_t *)a7 = 0x1002;
    if (g23 != 1) {
        // 0x14000111a
        return result;
    }
    // 0x140001093
    int64_t result2; // 0x140001000
    int64_t v5; // 0x140001000
    int64_t v6; // 0x140001000
    if (g35 < 1000) {
        // 0x1400010bd
        if ((int32_t)function_140002a10() < 1000) {
            // 0x1400010d8
            if ((char)function_14000137c() == 0) {
                // 0x1400010ea
                result2 = function_1400052a4(a1, a2, a3, a4, a5, a6, a7);
            } else {
                // 0x1400010e1
                result2 = function_140004958(v3 & -256 | 1, v2);
            }
            // 0x14000111a
            return result2;
        }
        // 0x1400010c7
        v5 = function_140002a10();
        v6 = (int64_t)"399:g_NfeFlowListSize is too big";
    } else {
        // 0x1400010a4
        v5 = g35;
        v6 = (int64_t)"393:NfeEventList is too big";
    }
    // 0x1400010ae
    result2 = function_140001804((char *)v6, 0xc0000001, v5 & 0xffffffff, 0);
    // 0x14000111a
    return result2;
}

// Address range: 0x140001140 - 0x140001250
int64_t function_1400013fc(int64_t a1, int64_t a2, int64_t a3, int32_t a4, int64_t a5, uint32_t a6) {
    int64_t v1 = *(int64_t *)((int64_t)g14 + 64); // 0x14000143d
    function_14000199c(v1, a2 & -256 | 5, 1, 11, (int64_t)&g2);
    int64_t v2 = 0; // 0x140001463
    int64_t v3; // 0x1400013fc
    if ((v3 & 32) != 0) {
        // 0x140001465
        v2 = (int64_t)*(int32_t *)(a3 + 64);
    }
    uint32_t v4 = (int32_t)a1; // 0x140001469
    int64_t v5; // 0x1400013fc
    int64_t v6; // 0x1400013fc
    int64_t v7; // 0x1400013fc
    int64_t v8; // 0x1400013fc
    if (v4 < 8) {
        if ((1 << v4 % 32 & 148) == 0) {
            goto lab_0x1400014ba;
        } else {
            int64_t v9 = function_1400038d8(a2); // 0x14000147b
            int64_t v10 = *(int64_t *)(v9 + 8); // 0x140001480
            int64_t v11 = (int64_t)*(int32_t *)v9; // 0x140001484
            int64_t v12 = function_140003c1c(a2); // 0x14000148f
            v7 = 0;
            v8 = v10;
            v5 = v2;
            v6 = v11;
            if (*(int32_t *)v12 != 0) {
                int64_t v13 = *(int64_t *)*(int64_t *)(v12 + 8); // 0x14000149c
                v7 = 0;
                v8 = v10;
                v5 = v2;
                v6 = v11;
                if (v13 != 0) {
                    int64_t v14 = *(int64_t *)(v13 + 8); // 0x1400014a4
                    v7 = 0;
                    v8 = v10;
                    v5 = v2;
                    v6 = v11;
                    if (v14 != 0) {
                        // 0x1400014ad
                        v7 = *(int64_t *)v14;
                        v8 = v10;
                        v5 = v2;
                        v6 = v11;
                    }
                }
            }
            goto lab_0x1400014eb;
        }
    } else {
        goto lab_0x1400014ba;
    }
  lab_0x1400014ba:;
    int64_t v15; // 0x1400013fc
    int64_t v16; // 0x1400013fc
    int64_t v17; // 0x1400013fc
    switch (v4) {
        case 3: {
            goto lab_0x1400014e2;
        }
        case 6: {
            goto lab_0x1400014e2;
        }
        default: {
            int64_t v18 = a1 & 0xffffffff; // 0x14000141b
            v16 = v18;
            v15 = v18;
            v17 = (int64_t)"127:Unknown event type";
            goto lab_0x1400014ce;
        }
    }
  lab_0x1400014e2:
    // 0x1400014e2
    v7 = 0;
    v8 = 0;
    v5 = v2;
    v6 = 0;
    if (a4 != 0) {
        // 0x1400014e7
        v7 = 0;
        v8 = 0;
        v5 = (int64_t)*(int32_t *)((int64_t)a4 + 32);
        v6 = 0;
    }
    goto lab_0x1400014eb;
  lab_0x1400014eb:;
    int32_t v19 = v6;
    uint32_t v20 = v19 + a6; // 0x1400014f2
    if (v20 < 0xf4241) {
        int64_t * v21 = ExAllocatePoolWithTag((int64_t)g42, v20 + 304, 0x746e7645); // 0x140001521
        if (v21 != NULL) {
            int64_t result = (int64_t)v21; // 0x140001521
            v16 = 304;
            function_140005d00(result, 0, 304);
            *(int32_t *)v21 = 304;
            *(int32_t *)(result + 24) = v20;
            *(int32_t *)(result + 28) = v19;
            *(int32_t *)(result + 32) = v4;
            *(int32_t *)(result + 36) = (int32_t)v5;
            int64_t v22 = function_140003920(a2); // 0x140001566
            char * v23 = (char *)(result + 176); // 0x140001574
            *v23 = (char)((int32_t)v22 == 1);
            *(int32_t *)(result + 180) = (int32_t)function_140003b1c(a2) % 256;
            if (v7 != 0) {
                // 0x140001595
                v16 = 128;
                function_140003880(result + 40, v7, 128);
            }
            if (v6 != 0) {
                // 0x1400015ac
                v16 = v6;
                function_1400059c0(result + 304, v8, v6, (int64_t)&g80);
            }
            int32_t v24; // 0x1400013fc
            int64_t v25; // 0x1400013fc
            if (a6 == 0) {
                // 0x1400015c0
                v24 = v16;
                v25 = v16;
            } else {
                int64_t v26 = a6; // 0x1400014eb
                v16 = v26;
                function_1400059c0(result + 304 + v6, a5, v26, (int64_t)&g80);
                v24 = a6;
                v25 = v26;
            }
            int64_t v27 = v25 & -256; // 0x1400015f2
            function_140003b78(a2, result + 248, v27 | (int64_t)(*v23 == 0));
            function_140003b78(a2, result + 276, v27 | (int64_t)*v23);
            int32_t v28 = v24; // 0x140001617
            if ((int16_t)v24 < 0) {
                // 0x140001619
                *(int64_t *)(result + 192) = *(int64_t *)(a3 + 112);
                v28 = *(int32_t *)&v16;
            }
            // 0x140001626
            if ((v28 & 2) != 0) {
                // 0x14000162a
                *(int64_t *)(result + 168) = *(int64_t *)(a3 + 32);
            }
            // 0x140001638
            return result;
        }
        // 0x14000152f
        v16 = 0x746e7645;
        v15 = 0x746e7645;
        v17 = (int64_t)"142:ExAllocatePoolWithTag failed";
    } else {
        int64_t v29 = v20; // 0x1400014f2
        v16 = v29;
        v15 = v29;
        v17 = (int64_t)"135:Size is too big";
    }
    goto lab_0x1400014ce;
  lab_0x1400014ce:
    // 0x1400014ce
    function_140001804((char *)v17, 0xc0000001, v15, 0);
    // 0x140001638
    return 0;
}

// Address range: 0x140001658 - 0x1400016b7
int64_t function_140001140(uint64_t a1, int64_t a2, int64_t a3) {
    int64_t v1 = a2 & -256 | 5; // 0x14000116d
    int64_t v2 = *(int64_t *)((int64_t)g14 + 64); // 0x14000117e
    function_140001b5c(v2, v1, 1, 20, (int64_t)&g2);
    if (a3 == 0) {
        int64_t v3 = (int16_t)a1 != 0 ? a1 % 0x10000 : 0xc0000001; // 0x1400011a4
        // 0x14000123b
        return function_140001804("338:NfeCalloutFlowDelete: flowContext=0", v3, a2 & 0xffffffff, 0);
    }
    // 0x1400011b7
    function_140002a18(a3);
    int64_t v4 = v1; // 0x1400011c6
    if (g23 != 0) {
        int64_t * v5 = ExAllocatePoolWithTag((int64_t)g42, 304, 0x746e7645); // 0x1400011db
        if (v5 != NULL) {
            int64_t v6 = (int64_t)v5; // 0x1400011db
            function_140005d00(v6, 0, 304);
            *(int32_t *)v5 = 304;
            *(int32_t *)(v6 + 32) = 5;
            *(int64_t *)(v6 + 168) = *(int64_t *)(a3 + 16);
            *(int32_t *)(v6 + 36) = *(int32_t *)(a3 + 32);
            function_14000129c(v6, 0);
            v4 = 0;
        } else {
            // 0x1400011e9
            function_140001804("349:ExAllocatePoolWithTag failed", 0xc0000001, 0, 0);
            v4 = 0xc0000001;
        }
    }
    // 0x140001233
    ExFreePoolWithTag((int64_t *)a3, (int32_t)v4);
    // 0x14000123b
    return &g80;
}

// Address range: 0x140001250 - 0x140001294
int64_t function_140001250(int64_t a1, int64_t a2) {
    int32_t v1 = a1; // 0x140001254
    int64_t v2; // 0x140001284
    if (v1 == 0) {
        // 0x140001269
        v2 = *(int64_t *)((int64_t)g14 + 64);
        function_14000199c(v2, a2 & -256 | 4, 1, 18, (int64_t)&g2);
        // 0x14000128d
        return 0;
    }
    if (v1 != 1) {
        // 0x14000128d
        return 0;
    }
    int64_t v3 = a1 + 18 & 0xffffffff;
    v2 = *(int64_t *)((int64_t)g14 + 64);
    function_14000199c(v2, a2 & -256 | 4, 1, v3, (int64_t)&g2);
    // 0x14000128d
    return 0;
}

// Address range: 0x140001294 - 0x14000129b
int64_t function_14000129c(int64_t a1, int32_t a2) {
    int64_t v1 = a2;
    int64_t v2 = *(int64_t *)((int64_t)g14 + 64); // 0x1400012de
    function_140001a64(v2, v1 & -256 | 5, 1, 12, (int64_t)&g2);
    int64_t v3 = KeQueryUnbiasedInterruptTime(); // 0x1400012e9
    int64_t v4; // bp-40, 0x14000129c
    int64_t v5 = &v4; // 0x1400012ef
    KeAcquireInStackQueuedSpinLock((int32_t *)&g79, (struct _KLOCK_QUEUE_HANDLE *)&v4);
    char v6 = 0; // 0x140001307
    char v7; // 0x14000129c
    int64_t v8; // 0x14000129c
    if (a2 == 0) {
        goto lab_0x140001310;
    } else {
        // 0x140001309
        v6 = *(char *)(v1 + 64);
        v8 = v5;
        v7 = v6;
        if (v6 != 0) {
            goto lab_0x14000134c;
        } else {
            goto lab_0x140001310;
        }
    }
  lab_0x140001310:
    // 0x140001310
    *(int64_t *)(a1 + 208) = v3;
    int64_t v9 = g37; // 0x14000132c
    if (*(int64_t *)g37 != (int64_t)&g36) {
        // 0x14000132e
        __asm_int(41);
        v9 = 3;
    }
    int64_t v10 = a1 + 8; // 0x140001325
    *(int64_t *)v10 = (int64_t)&g36;
    *(int64_t *)(a1 + 16) = v9;
    *(int64_t *)v9 = v10;
    g35++;
    g37 = v10;
    v8 = &g36;
    v7 = v6;
    goto lab_0x14000134c;
  lab_0x14000134c:
    // 0x14000134c
    KeReleaseInStackQueuedSpinLock((struct _KLOCK_QUEUE_HANDLE *)&v4);
    int64_t result = (int64_t)&g80 & -256; // 0x14000135a
    if (v7 != 1) {
        // 0x140001360
        result = function_140004f34(v5, v8) & -256 | 1;
    }
    // 0x140001367
    return result;
}

// Address range: 0x14000137c - 0x1400013fb
int64_t function_140002a74(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    int64_t v1 = a2 & -256 | 5; // 0x140002ab5
    int64_t v2 = *(int64_t *)((int64_t)g14 + 64); // 0x140002ab7
    function_14000199c(v2, v1, 1, 11, (int64_t)&g6);
    int64_t result = function_140002de0(0, v1, 1, 11); // 0x140002ac6
    if (g23 == 0) {
        // 0x140002bc8
        return result;
    }
    // 0x140002ad8
    int64_t v3; // 0x140002a74
    if (g51 != 0) {
        int64_t v4 = *(int64_t *)(a2 + 216); // 0x140002ae4
        v3 = v4;
        if (v4 != 0) {
            int64_t result2 = FwpsQueryConnectionRedirectState0((int64_t *)v4, (int64_t *)g51, NULL); // 0x140002af3
            if ((int32_t)result2 != 0) {
                // 0x140002bc8
                return result2;
            }
        }
    }
    int64_t v5 = 0; // bp-40, 0x140002b00
    int64_t v6 = function_1400013fc(2, a1, a2, 0, 0, 0); // 0x140002b1d
    int64_t v7 = 0; // 0x140002b30
    int64_t v8 = a1; // 0x140002b30
    int64_t v9 = 0; // 0x140002b30
    int64_t v10; // 0x140002a74
    int32_t v11; // 0x140002a74
    int64_t v12; // 0x140002a74
    int64_t v13; // 0x140002a74
    if (v6 == 0) {
        goto lab_0x140002b8f;
    } else {
        // 0x140002b32
        if ((char)function_140003b1c(a1) == 17) {
            int64_t v14 = function_140003a6c(a1, 0); // 0x140002b43
            uint32_t v15 = g26 & -240;
            int64_t v16 = v15; // 0x140002b50
            if ((g26 & 8) == 0) {
                // 0x140002be7
                if ((char)v15 == 0) {
                    // 0x140002bc8
                    return function_140001294(v6, v16);
                }
            } else {
                // 0x140002b5c
                if ((int16_t)v14 != 443) {
                    // 0x140002bc8
                    return function_140001294(v6, v16);
                }
            }
        }
        int32_t v17 = FwpsAcquireClassifyHandle0((int64_t *)a3, 0, &v5); // 0x140002b74
        v11 = v17;
        v12 = 0;
        v10 = 0;
        v13 = (int64_t)"260:FwpsAcquireClassifyHandle0 failed";
        if (v17 >= 0) {
            // 0x140002bf9
            *(int64_t *)(v6 + 184) = v5;
            int32_t * v18 = (int32_t *)(a5 + 24); // 0x140002c08
            *v18 = *v18 & -2;
            *(int32_t *)a5 = 0x1001;
            uint16_t v19 = *(int16_t *)&v3; // 0x140002c21
            int64_t v20 = function_140002d10(v5, v19, a5, a5, *(int64_t *)(v6 + 192)); // 0x140002c2a
            v7 = 0;
            v8 = v19;
            v9 = 0;
            if (v20 == 0) {
                goto lab_0x140002b8f;
            } else {
                int32_t v21 = FwpsPendClassify0(v5, a5, 0, (struct FWPS_CLASSIFY_OUT0_ *)a5); // 0x140002c49
                v11 = v21;
                v12 = v20;
                v10 = a5;
                v13 = (int64_t)"276:FwpsPendClassify0 failed";
                if (v21 >= 0) {
                    // 0x140002c5e
                    function_140002cb0(v20);
                    // 0x140002bc8
                    return function_140001294(v6, a5);
                }
                goto lab_0x140002b84;
            }
        } else {
            goto lab_0x140002b84;
        }
    }
  lab_0x140002b8f:;
    int32_t * v22 = (int32_t *)(a5 + 24); // 0x140002b8f
    *v22 = *v22 | 1;
    *(int32_t *)a5 = 0x1002;
    int64_t v23 = v7; // 0x140002b9c
    if (v6 != 0) {
        // 0x140002b9e
        ExFreePoolWithTag((int64_t *)v6, (int32_t)v8);
        v23 = &g80;
    }
    int64_t v24 = v23; // 0x140002ba9
    if (v9 != 0) {
        // 0x140002bab
        ExFreePoolWithTag((int64_t *)v9, 0x6e6f4352);
        v24 = &g80;
    }
    // 0x140002bb9
    v3 = v5;
    int64_t result3 = v24; // 0x140002bc1
    if (v5 != 0) {
        // 0x140002bc3
        FwpsReleaseClassifyHandle0(v5);
        result3 = &g80;
    }
    // 0x140002bc8
    return result3;
  lab_0x140002b84:;
    int64_t v25 = v11;
    v3 = v13;
    int64_t v26 = *(int64_t *)(a2 + 64); // 0x140002b84
    v7 = function_140001988((char *)v13, v25, (int32_t)v26, v10);
    v8 = v25;
    v9 = v12;
    goto lab_0x140002b8f;
}

// Address range: 0x140002c68 - 0x140002c9c
int64_t function_140002fe8(int64_t a1, int64_t a2) {
    int64_t v1 = *(int64_t *)((int64_t)g14 + 64); // 0x14000302a
    function_14000199c(v1, a2 & -256 | 5, 1, 10, (int64_t)&g6);
    int64_t v2 = function_140002ee4((int32_t)*(int64_t *)(a1 + 184), 0, 0, 0); // 0x140003046
    if (v2 == 0) {
        // 0x1400031e2
        return function_1400055d0(g16);
    }
    // 0x14000305d
    g50 = 0;
    int32_t * v3 = (int32_t *)(a1 + 204); // 0x140003064
    int64_t * v4; // 0x140002fe8
    if ((*v3 & 2) == 0) {
        // 0x14000305d
        v4 = (int64_t *)(v2 + 16);
    } else {
        int64_t v5 = *(int64_t *)(v2 + 40); // 0x140003072
        int64_t v6; // bp-72, 0x140002fe8
        int64_t v7 = &v6; // 0x140003076
        int64_t * v8 = (int64_t *)(v2 + 16);
        v6 = 0;
        int32_t v9 = FwpsAcquireWritableLayerDataPointer0(*v8, v5, 0, (int64_t **)&v6, NULL); // 0x14000308c
        if (v9 >= 0) {
            int32_t * v10 = (int32_t *)(v6 + 264); // 0x1400030b0
            if (*v10 == 0) {
                // 0x1400030bd
                *v10 = g25;
                if (g51 != 0) {
                    // 0x1400030d5
                    *(int64_t *)(v6 + 288) = g51;
                }
                int64_t v11 = v6 + 128; // 0x1400030e4
                uint16_t v12 = *(int16_t *)v11; // 0x1400030e4
                if (v12 != 2) {
                    if (v12 != 23) {
                        // 0x140003134
                        function_140001988("177:Unsupported remote address family", 0xc0000001, (int32_t)v12, v7);
                        *(int32_t *)(v6 + 264) = 0;
                    } else {
                        // 0x140003108
                        __asm_movups_1(*(int128_t *)v11, __asm_movups(*(int128_t *)(a1 + 276)));
                        *(int64_t *)(v6 + 144) = __asm_movsd_2(__asm_movsd(*(int64_t *)(a1 + 292)));
                        *(int32_t *)(v6 + 152) = *(int32_t *)(a1 + 300);
                    }
                } else {
                    int64_t v13 = __asm_movdqu(__asm_movups(*(int128_t *)(a1 + 276))); // 0x1400030f8
                    *(int128_t *)v11 = (int128_t)v13;
                }
            }
            // 0x140003154
            FwpsApplyModifiedLayerData0(*v8, (int64_t *)v6, 0);
            v4 = v8;
        } else {
            int64_t v14 = *v8; // 0x140003095
            function_140001988("159:FwpsAcquireWritableLayerDataPointer0 failed", (int64_t)v9, (int32_t)v14, v7);
            v4 = v8;
        }
    }
    // 0x140003164
    int128_t v15; // bp-64, 0x140002fe8
    __asm_movups_1(v15, __asm_movups(*(int128_t *)(v2 + 48)));
    int128_t v16; // 0x140002fe8
    __asm_movups_1(v16, __asm_movups(*(int128_t *)(v2 + 64)));
    __asm_movsd_2(__asm_movsd(*(int64_t *)(v2 + 80)));
    int64_t v17 = *v4; // 0x140003184
    int64_t v18 = v2; // 0x14000318a
    if ((*v3 & 4) != 0) {
        // 0x14000318c
        v18 = v2;
        if (g31 == 0 != (g32 == 0)) {
            // 0x14000319e
            *(char *)(v2 + 32) = 1;
            function_140002cb0(v2);
            v18 = 0;
        }
    }
    // 0x1400031ac
    v15 = 0x1002;
    FwpsCompleteClassify0(v17, 0, (struct FWPS_CLASSIFY_OUT0_ *)&v15);
    FwpsReleaseClassifyHandle0(v17);
    if (v18 != 0) {
        // 0x1400031d2
        ExFreePoolWithTag((int64_t *)v18, 0x6e6f4352);
    }
    // 0x1400031e2
    return function_1400055d0(g16);
}

// Address range: 0x140003210 - 0x140003453
int64_t function_140002de0(uint32_t a1, int64_t a2, int64_t a3, int64_t a4) {
    int64_t v1 = a1 % 256; // 0x140002df4
    int64_t v2 = a3 & -256 | v1; // 0x140002df7
    int64_t v3 = (char)a1 == 0; // 0x140002dff
    int64_t v4 = a4 & -256 | v3; // 0x140002e05
    int64_t v5 = function_140002ee4(0, 0, v2, v4); // 0x140002e0a
    if (v5 == 0) {
        // 0x140002ebf
        return 0;
    }
    int64_t v6 = 0;
    int64_t v7 = v6; // 0x140002e1f
    int64_t v8 = v2; // 0x140002e1f
    int64_t * v9; // 0x140002de0
    int32_t * v10; // 0x140002e46
    if (*(char *)(v5 + 32) == 0) {
        // 0x140002e21
        v9 = (int64_t *)(v5 + 16);
        v7 = v6;
        if ((char)a1 == 0) {
            // 0x140002e26
            function_140001988("108:Abandoned redirection request detected", 0xc0000001, (int32_t)*v9, v4);
            v7 = 1;
        }
        // 0x140002e3e
        v8 = v5 + 48;
        v10 = (int32_t *)(v5 + 72);
        *v10 = *v10 | 1;
        *(int32_t *)v8 = 0x1002;
        FwpsCompleteClassify0(*v9, 0, (struct FWPS_CLASSIFY_OUT0_ *)v8);
        FwpsReleaseClassifyHandle0(*v9);
    }
    int64_t v11 = v7;
    ExFreePoolWithTag((int64_t *)v5, 0x6e6f4352);
    int64_t v12 = v4 & -256 | v3; // 0x140002e6f
    int64_t v13 = v8 & -256 | v1; // 0x140002e72
    int64_t result = function_140002ee4(0, 0, v13, v12); // 0x140002e79
    while (result != 0) {
        int64_t v14 = v12;
        v6 = v11;
        int64_t v15 = result;
        int64_t v16 = v6; // 0x140002e1f
        v8 = v13;
        if (*(char *)(v15 + 32) == 0) {
            // 0x140002e21
            v9 = (int64_t *)(v15 + 16);
            v7 = v6;
            if ((char)a1 == 0) {
                int64_t v17 = *v9; // 0x140002e26
                function_140001988("108:Abandoned redirection request detected", 0xc0000001, (int32_t)v17, v14);
                v7 = 1;
            }
            // 0x140002e3e
            v8 = v15 + 48;
            v10 = (int32_t *)(v15 + 72);
            *v10 = *v10 | 1;
            *(int32_t *)v8 = 0x1002;
            FwpsCompleteClassify0(*v9, 0, (struct FWPS_CLASSIFY_OUT0_ *)v8);
            FwpsReleaseClassifyHandle0(*v9);
            v16 = v7;
        }
        // 0x140002e61
        v11 = v16;
        ExFreePoolWithTag((int64_t *)v15, 0x6e6f4352);
        v12 = v14 & -256 | v3;
        v13 = v8 & -256 | v1;
        result = function_140002ee4(0, 0, v13, v12);
    }
    // 0x140002e86
    if ((char)v11 == 0) {
        // 0x140002ebf
        return result;
    }
    uint32_t v18 = g50 + 1; // 0x140002e91
    g50 = v18;
    int64_t result2 = v18; // 0x140002e9c
    if (v18 >= 3) {
        // 0x140002e9e
        function_140001988("125:Too many abandoned redirection requests detected. Engine emergency stop", 0xc0000001, v18, v12);
        g50 &= (int32_t)result;
        result2 = function_140004958((int64_t)"125:Too many abandoned redirection requests detected. Engine emergency stop" & -256 | 1, 0xc0000001);
    }
    // 0x140002ebf
    return result2;
}

// Address range: 0x140002ed4 - 0x140002edb
