//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ------------------------ Structures ------------------------

struct FWPM_ACTION0_ {
    int32_t e0;
    int64_t e1;
};

struct FWPM_DISPLAY_DATA0_ {
    int16_t * e0;
    int16_t * e1;
};

struct FWPS_ACTION0_ {
    int32_t e0;
    int32_t e1;
};

struct FWPS_CLASSIFY_OUT0_ {
    int32_t e0;
    int64_t e1;
    int64_t e2;
    int32_t e3;
    int32_t e4;
    int32_t e5;
};

struct FWPS_DISCARD_METADATA0_ {
    int64_t e0;
    int32_t e1;
    int64_t e2;
};

struct FWPS_INBOUND_FRAGMENT_METADATA0_ {
    int32_t e0;
    int16_t e1;
    int32_t e2;
};

struct FWPS_INCOMING_VALUES0_ {
    int16_t e0;
    int32_t e1;
    struct FWPS_INCOMING_VALUE0_ * e2;
};

struct FWP_BYTE_BLOB_ {
    int32_t e0;
    char * e1;
};

struct FWP_CONDITION_VALUE0_ {
    int64_t e0;
    int64_t e1;
};

struct FWPS_FILTER_CONDITION0_ {
    int16_t e0;
    int16_t e1;
    int64_t e2;
    struct FWP_CONDITION_VALUE0_ e3;
};

struct FWP_VALUE0_ {
    int64_t e0;
    int64_t e1;
};

struct FWPS_FILTER1_ {
    int64_t e0;
    struct FWP_VALUE0_ e1;
    int16_t e2;
    int16_t e3;
    int32_t e4;
    struct FWPS_FILTER_CONDITION0_ * e5;
    struct FWPS_ACTION0_ e6;
    int64_t e7;
    struct FWPM_PROVIDER_CONTEXT1_ * e8;
};

struct FWPS_INCOMING_VALUE0_ {
    struct FWP_VALUE0_ e0;
};

struct _EPROCESS {
    int32_t e0;
};

struct _IP_ADDRESS_PREFIX {
    int64_t e0;
    char e1;
};

struct _KSPIN_LOCK_QUEUE {
    struct _KSPIN_LOCK_QUEUE * e0;
    int32_t * e1;
};

struct _KLOCK_QUEUE_HANDLE {
    struct _KSPIN_LOCK_QUEUE e0;
    char e1;
};

struct _KSPIN_LOCK_QUEUE {
    struct _KSPIN_LOCK_QUEUE * e0;
    int32_t * e1;
};

struct _LARGE_INTEGER {
    int64_t e0;
};

struct _MDL {
    struct _MDL * e0;
    int16_t e1;
    int16_t e2;
    int16_t e3;
    int16_t e4;
    struct _EPROCESS * e5;
    int64_t * e6;
    int64_t * e7;
    int32_t e8;
    int32_t e9;
};

struct _NDIS_OBJECT_HEADER {
    char e0;
    char e1;
    int16_t e2;
};

struct _NDIS_GENERIC_OBJECT {
    struct _NDIS_OBJECT_HEADER e0;
    int64_t * e1;
    int64_t * e2;
    int64_t e3;
};

struct _NET_BUFFER {
    int64_t e0;
    int16_t e1;
    int16_t e2;
    int64_t * e3;
    int64_t * e4[2];
    int64_t * e5[6];
    int64_t * e6[4];
    struct _LARGE_INTEGER e7;
    int64_t e8;
};

struct _NET_BUFFER_LIST {
    int64_t e0;
    struct _NET_BUFFER_LIST_CONTEXT * e1;
    struct _NET_BUFFER_LIST * e2;
    int64_t * e3;
    int64_t * e4[2];
    int64_t * e5[4];
    int64_t * e6[2];
    int64_t * e7;
    int64_t * e8;
    int32_t e9;
    int32_t e10;
    int32_t e11;
    int64_t e12;
    int64_t * e13[1];
};

struct _NET_BUFFER_LIST_CONTEXT {
    int64_t e0;
    int16_t e1;
    int16_t e2;
    char e3[1];
};

struct _NET_BUFFER_LIST_POOL_PARAMETERS {
    struct _NDIS_OBJECT_HEADER e0;
    char e1;
    char e2;
    int16_t e3;
    int32_t e4;
    int32_t e5;
};

struct _OSVERSIONINFOW {
    int32_t e0;
    int32_t e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    int16_t e5[128];
};

struct _SEC_WINNT_AUTH_IDENTITY_W {
    int16_t * e0;
    int32_t e1;
    int16_t * e2;
    int32_t e3;
    int16_t * e4;
    int32_t e5;
    int32_t e6;
};

struct _SID_IDENTIFIER_AUTHORITY {
    char e0[6];
};

struct _SID {
    char e0;
    char e1;
    struct _SID_IDENTIFIER_AUTHORITY e2;
    int32_t e3[1];
};

struct _TYPEDEF_GUID {
    int32_t e0;
    int16_t e1;
    int16_t e2;
    char e3[8];
};

struct FWPM_CALLOUT0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    struct _TYPEDEF_GUID e5;
    int32_t e6;
};

struct FWPM_FILTER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    struct _TYPEDEF_GUID e5;
    struct _TYPEDEF_GUID e6;
    struct FWP_VALUE0_ e7;
    int32_t e8;
    struct FWPM_FILTER_CONDITION0_ * e9;
    struct FWPM_ACTION0_ e10;
    int64_t e11;
    struct _TYPEDEF_GUID * e12;
    int64_t e13;
    struct FWP_VALUE0_ e14;
};

struct FWPM_FILTER_CONDITION0_ {
    struct _TYPEDEF_GUID e0;
    int64_t e1;
    struct FWP_CONDITION_VALUE0_ e2;
};

struct FWPM_PROVIDER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct FWP_BYTE_BLOB_ e3;
    int16_t * e4;
};

struct FWPM_PROVIDER_CONTEXT1_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    int64_t e5;
    int64_t e6;
    int64_t e7;
};

struct FWPM_SESSION0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    struct _SID * e5;
    int16_t * e6;
    bool e7;
};

struct FWPM_SUBLAYER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    int16_t e5;
};

struct FWPS_CALLOUT1_ {
    struct _TYPEDEF_GUID e0;
    int32_t e1;
    void (*e2)(struct FWPS_INCOMING_VALUES0_ *, struct FWPS_INCOMING_METADATA_VALUES0_ *, int64_t *, int64_t *, struct FWPS_FILTER1_ *, int64_t, struct FWPS_CLASSIFY_OUT0_ *);
    int32_t (*e3)(int64_t, struct _TYPEDEF_GUID *, struct FWPS_FILTER1_ *);
    void (*e4)(int16_t, int32_t, int64_t);
};

struct _TYPEDEF_SCOPE_ID__PSCOPE_ID {
    int64_t e0;
};

struct FWPS_INCOMING_METADATA_VALUES0_ {
    int32_t e0;
    int32_t e1;
    int64_t e2;
    struct FWPS_DISCARD_METADATA0_ e3;
    int64_t e4;
    int32_t e5;
    int32_t e6;
    struct FWP_BYTE_BLOB_ * e7;
    int64_t e8;
    int64_t e9;
    int32_t e10;
    int32_t e11;
    int32_t e12;
    struct FWPS_INBOUND_FRAGMENT_METADATA0_ e13;
    int32_t e14;
    int64_t * e15;
    int64_t e16;
    struct _TYPEDEF_SCOPE_ID__PSCOPE_ID e17;
    struct _WSACMSGHDR * e18;
    int32_t e19;
    int64_t e20;
    int64_t * e21;
    int32_t e22;
    struct _IP_ADDRESS_PREFIX e23;
    int16_t e24;
    int64_t e25;
    int32_t e26;
    int32_t e27;
    struct sockaddr * e28;
    int64_t * e29;
    int32_t e30;
    int32_t e31;
    int32_t e32;
    int32_t e33;
    int32_t e34;
    int16_t e35;
    int32_t e36;
    int64_t * e37;
    int64_t * e38;
    int64_t e39;
};

struct FWPS_TRANSPORT_SEND_PARAMS0_ {
    char * e0;
    struct _TYPEDEF_SCOPE_ID__PSCOPE_ID e1;
    int64_t * e2;
    int32_t e3;
};

struct _UNICODE_STRING {
    int16_t e0;
    int16_t e1;
    int16_t * e2;
};

struct _WSACMSGHDR {
    int32_t e0;
    int32_t e1;
    int32_t e2;
};

struct sockaddr {
    int16_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(int64_t a1, int64_t a2);
/* Extracted from ProxifierDrv.sys (RetDec). WFP hooks subset. */

int64_t function_140002280(int64_t a1, int64_t a2, int64_t a3) {
    int64_t v1 = a3;
    int64_t v2 = *(int64_t *)((int64_t)g14 + 64); // 0x1400022b1
    function_14000199c(v2, a2 & -256 | 5, 1, 11, (int64_t)&g4);
    int32_t * v3 = (int32_t *)(a1 + 4); // 0x1400022be
    int64_t * v4 = ExAllocatePoolWithTag((int64_t)g42, *v3, 0x70647549); // 0x1400022cd
    if (v4 == NULL) {
        // 0x1400022db
        function_140001988("35:ExAllocatePoolWithTag failed", 0xc0000017, 0, 11);
        // 0x140002439
        return 0xc0000017;
    }
    uint32_t v5 = *v3; // 0x1400022f6
    function_1400059c0((int64_t)v4, a1 + 56, (int64_t)v5, (int64_t)&g80);
    v1 = 0;
    int64_t * v6 = IoAllocateMdl(v4, *v3, 0, 0, NULL); // 0x14000231e
    int64_t v7 = 0xc0000017; // 0x14000232a
    if (v6 != NULL) {
        // 0x140002336
        MmBuildMdlForNonPagedPool(v6);
        int32_t v8 = *v3; // 0x14000233f
        uint32_t v9 = FwpsAllocateNetBufferAndNetBufferList0((int64_t *)g55, 0, 0, (struct _MDL *)v6, 0, v8, (struct _NET_BUFFER_LIST **)&v1); // 0x140002364
        v7 = v9;
        if (v9 >= 0) {
            char * v10 = (char *)(a1 + 48); // 0x140002386
            int32_t v11; // 0x140002280
            if (*v10 == 0) {
                int64_t v12 = *(int64_t *)(a1 + 40); // 0x1400023c7
                int32_t v13 = *(int32_t *)(a1 + 16); // 0x1400023df
                int16_t v14 = *(int16_t *)(a1 + 8); // 0x1400023e6
                v11 = FwpsInjectTransportSendAsync0((int64_t *)g52, NULL, v12, 0, NULL, v14, (int64_t)v13, (struct _NET_BUFFER_LIST *)(v1 & 0xffffffff), (void (*)(int64_t *, struct _NET_BUFFER_LIST *, char))0x140002460, v6);
            } else {
                int32_t v15 = *(int32_t *)(a1 + 24); // 0x1400023a2
                int32_t v16 = *(int32_t *)(a1 + 20); // 0x1400023a9
                int32_t v17 = *(int32_t *)(a1 + 16); // 0x1400023b0
                int16_t v18 = *(int16_t *)(a1 + 8); // 0x1400023b7
                v11 = FwpsInjectTransportReceiveAsync0((int64_t *)g52, NULL, NULL, 0, v18, (int64_t)v17, v16, v15, (struct _NET_BUFFER_LIST *)v1, (void (*)(int64_t *, struct _NET_BUFFER_LIST *, char))0x140002460, v6);
            }
            // 0x1400023fa
            v7 = v11;
            if (v11 >= 0) {
                // 0x140002439
                return v7 & 0xffffffff;
            }
            // 0x140002400
            function_140001988("88:FwpsInjectTransport(Receive/Send)Async0 failed", v7, (int32_t)*v10, 0);
        }
        // 0x140002413
        IoFreeMdl(v6);
    }
    // 0x14000241c
    ExFreePoolWithTag(v4, 0x70647549);
    if (v1 != 0) {
        // 0x140002434
        FwpsFreeNetBufferList0((struct _NET_BUFFER_LIST *)v1);
    }
    // 0x140002439
    return v7 & 0xffffffff;
}

// Address range: 0x140002460 - 0x1400024c8
int64_t function_140001ed8(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5) {
    int64_t v1 = *(int64_t *)((int64_t)g14 + 64); // 0x140001f37
    function_14000199c(v1, a2 & -256 | 5, 1, 12, (int64_t)&g4);
    if (*(int32_t *)(a4 + 32) == g25) {
        // 0x14000225b
        return function_1400055d0(g16);
    }
    int32_t v2 = FwpsQueryPacketInjectionState0((int64_t *)g52, (struct _NET_BUFFER_LIST *)a3, NULL); // 0x140001f65
    if (v2 == 1) {
        // 0x14000225b
        return function_1400055d0(g16);
    }
    if (v2 == 3) {
        // 0x140001f73
        if (g33 == 0) {
            // 0x140001f80
            function_140001988("163:FWPS_PACKET_PREVIOUSLY_INJECTED_BY_SELF", 0xc0000001, 0, 12);
            g33 = 1;
        }
        // 0x14000225b
        return function_1400055d0(g16);
    }
    int32_t v3 = a3;
    int32_t v4 = v3; // 0x140001fa8
    if (v2 == 2) {
        // 0x140001faa
        v4 = v3;
        if (g34 == 0) {
            // 0x140001fb3
            function_140001988("173:FWPS_PACKET_INJECTED_BY_OTHER", 0xc0000001, 0, 12);
            g34 = 1;
            v4 = -0x3fffffff;
        }
        // 0x140001fcb
        if (g30 == 0) {
            // 0x14000225b
            return function_1400055d0(g16);
        }
    }
    int64_t v5 = function_140003920(a1); // 0x140001fdb
    int64_t v6 = 0; // 0x140001feb
    if ((v4 & 1024) != 0) {
        // 0x140001fed
        v6 = (int64_t)*(int32_t *)(a2 + 44);
    }
    int64_t v7 = 0; // 0x140001ffc
    if ((v4 & 4) != 0) {
        // 0x140001ffe
        v7 = (int64_t)*(int32_t *)(a2 + 40);
    }
    int64_t * v8 = (int64_t *)(a3 + 8); // 0x140002007
    int64_t v9 = *v8; // 0x140002007
    int64_t v10 = (int64_t)"187:NET_BUFFER_LIST_FIRST_NB failed"; // 0x140002013
    int32_t v11 = 0; // 0x140002013
    int64_t v12 = 12; // 0x140002013
    int64_t v13 = 0xc0000001; // 0x140002013
    int64_t v14; // 0x140001ed8
    int64_t v15; // 0x140001ed8
    int32_t v16; // 0x140001fe3
    int32_t v17; // 0x140001ed8
    struct _NET_BUFFER * v18; // 0x14000200b
    if (v9 != 0) {
        // 0x14000202b
        v16 = v5;
        v17 = v6;
        v18 = (struct _NET_BUFFER *)v9;
        v14 = v9;
        v15 = 12;
        if (v16 != 1) {
            goto lab_0x140002052;
        } else {
            // 0x140002030
            v11 = v7;
            int32_t v19 = v11 + v17; // 0x140002030
            v14 = v9;
            v15 = 12;
            if (v19 == 0) {
                goto lab_0x140002052;
            } else {
                int32_t v20 = NdisRetreatNetBufferDataStart(v18, v19, 0, NULL); // 0x14000203b
                if (v20 >= 0) {
                    // 0x140002035
                    v14 = *v8;
                    v15 = 0;
                    goto lab_0x140002052;
                } else {
                    // 0x140002044
                    v10 = (int64_t)"196:NdisRetreatNetBufferDataStart failed";
                    v12 = 0;
                    v13 = v20;
                    goto lab_0x140002021;
                }
            }
        }
    } else {
        goto lab_0x140002021;
    }
  lab_0x140002021:
    // 0x140002021
    function_140001988((char *)v10, v13, v11, v12);
    // 0x14000225b
    return function_1400055d0(g16);
  lab_0x140002052:;
    // 0x140002052
    int64_t v21; // bp-1592, 0x140001ed8
    int64_t v22 = &v21; // 0x140002056
    uint32_t v23 = *(int32_t *)(v14 + 24); // 0x140002067
    function_140005d00(v22, 0, 1500);
    bool v24 = false; // 0x14000207b
    int64_t v25 = v22; // 0x14000207b
    if (v23 >= 1501) {
        int64_t * v26 = ExAllocatePoolWithTag((int64_t)g42, v23, 0x64504455); // 0x14000208b
        int64_t v27 = (int64_t)v26; // 0x14000208b
        v24 = false;
        v25 = v27;
        if (v26 == NULL) {
            // 0x140002099
            function_140001988("211:ExAllocatePoolWithTag failed", 0xc0000001, 0x64504455, v15);
            v24 = true;
            v25 = v27;
        }
    }
    int64_t * v28 = (int64_t *)v25; // 0x1400020c2
    int64_t * v29 = NdisGetDataBuffer(v18, v23, v28, 1, 0); // 0x1400020c2
    int64_t v30 = (int64_t)v29; // 0x1400020c2
    int32_t v31 = v7;
    int32_t v32 = v31 + v17; // 0x1400020d3
    int64_t v33 = 0; // 0x1400020da
    int64_t v34 = v30; // 0x1400020da
    int64_t v35 = (int64_t)"217:NdisGetDataBuffer failed"; // 0x1400020da
    int32_t v36; // 0x140001ed8
    int64_t v37; // 0x140001ed8
    if (v29 != NULL) {
        // 0x1400020e8
        v36 = v23;
        v37 = 0;
        if (v23 > v32) {
            // 0x1400020f1
            if ((g26 & 2) == 0) {
                goto lab_0x140002153;
            } else {
                int64_t v38 = (int64_t)v23 - v7 - v6; // 0x140002116
                if ((char)function_1400024c8(v7 + v6 + v30, (int32_t)v38, v16, v30 & -256 || (int64_t)(g26 & 4)) != 0) {
                    goto lab_0x140002153;
                } else {
                    int64_t v39 = v38 & 0xffffff00 | 5; // 0x14000213d
                    int64_t v40 = *(int64_t *)((int64_t)g14 + 64); // 0x14000213f
                    function_14000199c(v40, v39, 1, 13, (int64_t)&g4);
                    v36 = v39;
                    v37 = 0;
                    goto lab_0x14000218d;
                }
            }
        } else {
            goto lab_0x14000218d;
        }
    } else {
        goto lab_0x140002183;
    }
  lab_0x140002183:
    // 0x140002183
    function_140001988((char *)v35, 0xc0000001, v23, v34);
    v36 = -0x3fffffff;
    v37 = v33;
    goto lab_0x14000218d;
  lab_0x14000218d:;
    int64_t v41 = v37;
    int32_t v42 = v36; // 0x140002194
    if (v16 == 1 && v32 != 0) {
        // 0x14000219a
        NdisAdvanceNetBufferDataStart(v18, v32, 0, NULL);
        v42 = v32;
    }
    int32_t v43 = v42; // 0x1400021af
    if (!v24 && v25 != v22) {
        // 0x1400021bb
        ExFreePoolWithTag(v28, 0x746e7645);
        v43 = 0x746e7645;
    }
    if (v41 == 0) {
        // 0x14000225b
        return function_1400055d0(g16);
    }
    int32_t v44 = 0; // 0x1400021d9
    if ((v43 & 2048) != 0) {
        // 0x1400021db
        v44 = *(int32_t *)(a2 + 80);
    }
    // 0x1400021e3
    *(int32_t *)(v41 + 216) = v44;
    *(int32_t *)(v41 + 220) = (int32_t)function_140003954(a1, 0);
    *(int32_t *)(v41 + 224) = (int32_t)function_140003954(a1, 1);
    *(int32_t *)(v41 + 232) = v16 == 1 ? v31 : 0;
    *(int32_t *)(v41 + 228) = v17;
    *(int64_t *)(v41 + 240) = *(int64_t *)(v41 + 192);
    function_140001294(v41, 1);
    if (v16 != 0) {
        // 0x14000225b
        return function_1400055d0(g16);
    }
    // 0x140002240
    if (g26 % 2 != 0) {
        int32_t * v45 = (int32_t *)(a5 + 24); // 0x14000224a
        *v45 = *v45 & -2;
        int32_t * v46 = (int32_t *)(a5 + 28); // 0x14000224f
        *v46 = *v46 | 1;
        *(int32_t *)a5 = 0x1001;
    }
    // 0x14000225b
    return function_1400055d0(g16);
  lab_0x140002153:;
    int64_t v47 = function_1400013fc(3, a1, a2, (int32_t)a4, v30, v23); // 0x14000216f
    v33 = v47;
    v34 = a4;
    v35 = (int64_t)"236:CreateNfeEvent failed";
    v36 = a1;
    v37 = v47;
    if (v47 != 0) {
        goto lab_0x14000218d;
    } else {
        goto lab_0x140002183;
    }
}

// Address range: 0x140002280 - 0x140002451
int64_t function_140002460(int64_t a1, int64_t a2) {
    int64_t v1 = *(int64_t *)((int64_t)g14 + 64); // 0x14000248b
    function_14000199c(v1, a2 & -256 | 5, 1, 10, (int64_t)&g4);
    FwpsFreeNetBufferList0((struct _NET_BUFFER_LIST *)a2);
    if (a1 != 0) {
        // 0x1400024a5
        ExFreePoolWithTag((int64_t *)*(int64_t *)(a1 + 24), 0x70647549);
        IoFreeMdl((int64_t *)a1);
    }
    // 0x1400024bd
    return &g80;
}

// Address range: 0x1400024c8 - 0x14000252e
int64_t function_1400024c8(int64_t a1, uint32_t a2, int32_t a3, int64_t a4) {
    if (a2 < 12 || *(int16_t *)(a1 + 4) != 256) {
        // 0x140002513
        return a1 & -256;
    }
    if (a3 == 0) {
        // 0x1400024e9
        if (*(int16_t *)(a1 + 6) != 0 || *(int16_t *)(a1 + 8) != 0) {
            // 0x140002513
            return a1 & -256;
        }
    }
    uint32_t v1 = a2 - 2; // 0x1400024f7
    if (v1 <= 12) {
        // 0x140002513
        return a1 & -256;
    }
    int64_t v2 = a1 + 12; // 0x140002500
    int64_t v3 = 12;
    while (*(char *)v2 != 0) {
        int64_t v4 = v3 + 1; // 0x140002509
        v2++;
        if (v1 <= (int32_t)v4) {
            // 0x140002513
            return a1 & -256;
        }
        v3 = v4 & 0xffffffff;
    }
    if ((char)a4 == 0) {
        // 0x14000252b
        return a1 & -256 | 1;
    }
    char v5 = *(char *)((v3 + 2 & 0xffffffff) + a1); // 0x14000251e
    if (v5 != 1 == (v5 != 28)) {
        // 0x140002513
        return a1 & -256;
    }
    // 0x14000252b
    return a1 & -256 | 1;
}

// Address range: 0x140002530 - 0x140002678
int64_t function_140002530(int64_t a1, int64_t a2) {
    int64_t v1 = *(int64_t *)((int64_t)g14 + 64); // 0x140002564
    function_14000199c(v1, a2 & -256 | 5, 1, 12, (int64_t)&g5);
    return function_140001988("199:CalloutFlow no FWPS_METADATA_FIELD_FLOW_HANDLE", 0xc0000001, 0, 12);
}

// Address range: 0x140002678 - 0x1400026ac
int64_t function_140003210(int64_t a1, int64_t a2) {
    int32_t v1 = 276; // bp-344, 0x140003240
    if (RtlGetVersion((struct _OSVERSIONINFOW *)&v1) < 0) {
        goto lab_0x14000327d;
    } else {
        int32_t v2; // 0x140003210
        if (v2 < 7) {
            if (v2 < 2 || v2 != 6) {
                goto lab_0x14000327d;
            } else {
                // 0x140003269
                g42 = 512;
                *(int32_t *)&g43 = 0x40000000;
                goto lab_0x14000327d;
            }
        } else {
            // 0x140003269
            g42 = 512;
            *(int32_t *)&g43 = 0x40000000;
            goto lab_0x14000327d;
        }
    }
  lab_0x14000327d:
    // 0x14000327d
    g70 = 0;
    g71 = &g1;
    g74 = 1;
    g72 = 0;
    g73 = 0;
    g75 = 0;
    *(int32_t *)&g76 = 0;
    int64_t v3; // 0x140003210
    function_140017140((int64_t)&v1, a2, v3, v3, (int64_t)&g80);
    g73 = 0;
    function_140017090(a1, a2);
    int64_t v4 = *(int64_t *)((int64_t)g14 + 64); // 0x1400032ee
    function_14000199c(v4, a2 & -256 | 4, 1, 10, (int64_t)&g9);
    int64_t v5; // bp-400, 0x140003210
    function_140005d00((int64_t)&v5, 0, 56);
    v5 = 56;
    if ((int32_t)function_1400059a0() < 0) {
        int64_t v6 = *(int64_t *)((int64_t)g14 + 64); // 0x14000339c
        function_140001a64(v6, a1 & -256 | 2, 1, 11, (int64_t)&g9);
        // 0x1400033f3
        function_140017000(a1);
        // 0x14000342a
        return function_1400055d0(g16);
    }
    int64_t v7 = function_1400059a0(); // 0x1400033c1
    if (v7 != 0) {
        // 0x1400033fd
        function_140003454(v7, a1);
        int64_t v8 = *(int64_t *)((int64_t)g14 + 64); // 0x140003421
        function_14000199c(v8, a1 & -256 | 4, 1, 13, (int64_t)&g9);
        // 0x14000342a
        return function_1400055d0(g16);
    }
    int64_t v9 = *(int64_t *)((int64_t)g14 + 64); // 0x1400033e5
    function_140001a64(v9, v3 & -256 | 2, 1, v7 + 12 & 0xffffffff, (int64_t)&g9);
    // 0x1400033f3
    function_140017000(a1);
    // 0x14000342a
    return function_1400055d0(g16);
}

// Address range: 0x140003454 - 0x1400037a4
int64_t function_140003454(int64_t a1, int64_t a2) {
    int128_t v1 = __asm_movups(0x5c006500630069007600650044005c); // 0x14000347c
    int128_t v2 = __asm_movups(0x650069006600690078006f00720050); // 0x14000348d
    __asm_movups_1(0, v1);
    __asm_movsd_2(__asm_movsd(0x76007200440072));
    int128_t v3 = __asm_movaps(0x690076006500440073006f0044005c); // 0x1400034b8
    int128_t v4; // 0x140003454
    __asm_movups_1(v4, v2);
    int128_t v5 = __asm_movaps(0x62006f006c0047005c007300650063); // 0x1400034cc
    __asm_movaps_3(v3);
    int128_t v6 = __asm_movaps(0x690078006f00720050005c006c0061); // 0x1400034d7
    __asm_movaps_3(v5);
    int128_t v7 = __asm_movaps(0x76007200440072006500690066); // 0x1400034e2
    __asm_movaps_3(v6);
    int128_t v8 = __asm_movaps(0x47003b003b004100280050003a0044); // 0x1400034ed
    __asm_movaps_3(v7);
    int128_t v9 = __asm_movaps(0x28002900590053003b003b003b0041); // 0x1400034f8
    __asm_movaps_3(v8);
    int128_t v10 = __asm_movaps(0x470057004700520047003b003b0041); // 0x140003503
    __asm_movaps_3(v9);
    int128_t v11 = __asm_movaps(0x28002900410042003b003b003b0058); // 0x14000350e
    __asm_movaps_3(v10);
    int128_t v12 = __asm_movaps(0x470057004700520047003b003b0041); // 0x140003519
    __asm_movaps_3(v11);
    int128_t v13 = __asm_movaps(0x2900440057003b003b003b0058); // 0x140003524
    __asm_movaps_3(v12);
    int64_t v14 = a1; // bp-312, 0x14000352f
    __asm_movaps_3(v13);
    int64_t v15 = *(int64_t *)((int64_t)g14 + 64); // 0x140003570
    function_14000199c(v15, a2 & -256 | 5, 1, 14, (int64_t)&g9);
    function_1400059a0();
    function_1400059a0();
    int64_t v16 = function_1400059a0(); // 0x1400035d1
    int64_t v17; // 0x140003454
    int64_t v18; // 0x140003454
    int64_t v19; // 0x140003454
    int64_t v20; // 0x140003454
    if ((int32_t)v16 >= 0) {
        int64_t v21 = function_140004c20(a1, a1); // 0x14000360f
        if ((int32_t)v21 >= 0) {
            int64_t v22 = function_1400059a0(); // 0x14000363a
            if ((int32_t)v22 >= 0) {
                int64_t v23 = function_1400059a0(); // 0x140003669
                if ((int32_t)v23 >= 0) {
                    int64_t v24 = function_1400059a0(); // 0x140003698
                    if ((int32_t)v24 >= 0) {
                        int64_t v25 = function_140004ca8(0, 0); // 0x1400036b4
                        if ((int32_t)v25 >= 0) {
                            int64_t v26 = function_140003c64(function_1400059a0(), a2); // 0x1400036e9
                            int64_t v27 = v26 & 0xffffffff; // 0x1400036ee
                            v20 = a2;
                            v18 = v27;
                            v17 = 21;
                            if ((int32_t)v26 >= 0) {
                                // 0x1400036ff
                                function_1400059a0();
                                v19 = v27;
                                goto lab_0x140003718;
                            } else {
                                goto lab_0x1400035e1;
                            }
                        } else {
                            // 0x1400036bf
                            v20 = 0;
                            v18 = v25 & 0xffffffff;
                            v17 = 20;
                            goto lab_0x1400035e1;
                        }
                    } else {
                        // 0x1400036a4
                        v20 = 0;
                        v18 = v24 & 0xffffffff;
                        v17 = 19;
                        goto lab_0x1400035e1;
                    }
                } else {
                    // 0x140003675
                    v20 = &v14;
                    v18 = v23 & 0xffffffff;
                    v17 = 18;
                    goto lab_0x1400035e1;
                }
            } else {
                // 0x140003646
                v20 = a1;
                v18 = v22 & 0xffffffff;
                v17 = 17;
                goto lab_0x1400035e1;
            }
        } else {
            // 0x14000361a
            v20 = a1;
            v18 = v21 & 0xffffffff;
            v17 = 16;
            goto lab_0x1400035e1;
        }
    } else {
        // 0x1400035dd
        v20 = a1;
        v18 = v16 & 0xffffffff;
        v17 = 15;
        goto lab_0x1400035e1;
    }
  lab_0x1400035e1:;
    int64_t v28 = *(int64_t *)((int64_t)g14 + 64); // 0x1400035f6
    function_140001a64(v28, v20 & -256 | 2, 1, v17, (int64_t)&g9);
    v19 = v18;
    goto lab_0x140003718;
  lab_0x140003718:
    // 0x140003718
    if (v14 != 0) {
        // 0x140003722
        function_1400059a0();
    }
    int64_t v29 = v14; // 0x140003738
    if ((int32_t)v19 < 0) {
        int64_t v30 = v14 & -256 | 2; // 0x14000374e
        int64_t v31 = *(int64_t *)((int64_t)g14 + 64); // 0x140003755
        function_140001a64(v31, v30, 1, 22, (int64_t)&g9);
        v29 = v30;
    }
    int64_t v32 = *(int64_t *)((int64_t)g14 + 64); // 0x140003775
    function_14000199c(v32, v29 & -256 | 4, 1, 23, (int64_t)&g9);
    return function_1400055d0(g16);
}

// Address range: 0x1400037b0 - 0x140003805
int64_t function_1400037b0(int64_t a1, int64_t a2) {
    int64_t v1 = *(int64_t *)((int64_t)g14 + 64); // 0x1400037d4
    function_14000199c(v1, a2 & -256 | 5, 1, 24, (int64_t)&g9);
    return function_140017000(function_1400059a0());
}

// Address range: 0x140003810 - 0x140003845
int64_t function_140003810(int64_t a1, int64_t a2) {
    int64_t v1 = a2 & -256 | 5; // 0x14000382d
    int64_t v2 = *(int64_t *)((int64_t)g14 + 64); // 0x14000382f
    function_14000199c(v2, v1, 1, 25, (int64_t)&g9);
    return function_14000427c(v2, v1);
}

// Address range: 0x140003850 - 0x14000387d
int64_t function_140003850(int64_t a1, int64_t a2, int64_t a3, int64_t a4) {
    unsigned char v1 = (char)a2; // 0x140003850
    if (v1 >= 2) {
        // 0x14000387c
        int64_t result; // 0x140003850
        return result;
    }
    int64_t result2; // 0x140003850
    if (v1 == 0) {
        // 0x140003870
        *(char *)(a4 + 41) = 0;
        *(int32_t *)(a4 + 44) = 0;
        result2 = 0;
    } else {
        // 0x14000385b
        *(int32_t *)(a4 + 44) = *(int32_t *)(a3 + 4);
        *(char *)(a4 + 41) = *(char *)(a3 + 2);
        result2 = a3;
    }
    // 0x140003878
    *(int64_t *)(a4 + 24) = result2;
    // 0x14000387c
    return result2;
}

// Address range: 0x140003880 - 0x1400038d5
