//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ------------------------ Structures ------------------------

struct FWPM_ACTION0_ {
    int32_t e0;
    int64_t e1;
};

struct FWPM_DISPLAY_DATA0_ {
    int16_t * e0;
    int16_t * e1;
};

struct FWPS_ACTION0_ {
    int32_t e0;
    int32_t e1;
};

struct FWPS_CLASSIFY_OUT0_ {
    int32_t e0;
    int64_t e1;
    int64_t e2;
    int32_t e3;
    int32_t e4;
    int32_t e5;
};

struct FWPS_DISCARD_METADATA0_ {
    int64_t e0;
    int32_t e1;
    int64_t e2;
};

struct FWPS_INBOUND_FRAGMENT_METADATA0_ {
    int32_t e0;
    int16_t e1;
    int32_t e2;
};

struct FWPS_INCOMING_VALUES0_ {
    int16_t e0;
    int32_t e1;
    struct FWPS_INCOMING_VALUE0_ * e2;
};

struct FWP_BYTE_BLOB_ {
    int32_t e0;
    char * e1;
};

struct FWP_CONDITION_VALUE0_ {
    int64_t e0;
    int64_t e1;
};

struct FWPS_FILTER_CONDITION0_ {
    int16_t e0;
    int16_t e1;
    int64_t e2;
    struct FWP_CONDITION_VALUE0_ e3;
};

struct FWP_VALUE0_ {
    int64_t e0;
    int64_t e1;
};

struct FWPS_FILTER1_ {
    int64_t e0;
    struct FWP_VALUE0_ e1;
    int16_t e2;
    int16_t e3;
    int32_t e4;
    struct FWPS_FILTER_CONDITION0_ * e5;
    struct FWPS_ACTION0_ e6;
    int64_t e7;
    struct FWPM_PROVIDER_CONTEXT1_ * e8;
};

struct FWPS_INCOMING_VALUE0_ {
    struct FWP_VALUE0_ e0;
};

struct _EPROCESS {
    int32_t e0;
};

struct _IP_ADDRESS_PREFIX {
    int64_t e0;
    char e1;
};

struct _KSPIN_LOCK_QUEUE {
    struct _KSPIN_LOCK_QUEUE * e0;
    int32_t * e1;
};

struct _KLOCK_QUEUE_HANDLE {
    struct _KSPIN_LOCK_QUEUE e0;
    char e1;
};

struct _KSPIN_LOCK_QUEUE {
    struct _KSPIN_LOCK_QUEUE * e0;
    int32_t * e1;
};

struct _LARGE_INTEGER {
    int64_t e0;
};

struct _MDL {
    struct _MDL * e0;
    int16_t e1;
    int16_t e2;
    int16_t e3;
    int16_t e4;
    struct _EPROCESS * e5;
    int64_t * e6;
    int64_t * e7;
    int32_t e8;
    int32_t e9;
};

struct _NDIS_OBJECT_HEADER {
    char e0;
    char e1;
    int16_t e2;
};

struct _NDIS_GENERIC_OBJECT {
    struct _NDIS_OBJECT_HEADER e0;
    int64_t * e1;
    int64_t * e2;
    int64_t e3;
};

struct _NET_BUFFER {
    int64_t e0;
    int16_t e1;
    int16_t e2;
    int64_t * e3;
    int64_t * e4[2];
    int64_t * e5[6];
    int64_t * e6[4];
    struct _LARGE_INTEGER e7;
    int64_t e8;
};

struct _NET_BUFFER_LIST {
    int64_t e0;
    struct _NET_BUFFER_LIST_CONTEXT * e1;
    struct _NET_BUFFER_LIST * e2;
    int64_t * e3;
    int64_t * e4[2];
    int64_t * e5[4];
    int64_t * e6[2];
    int64_t * e7;
    int64_t * e8;
    int32_t e9;
    int32_t e10;
    int32_t e11;
    int64_t e12;
    int64_t * e13[1];
};

struct _NET_BUFFER_LIST_CONTEXT {
    int64_t e0;
    int16_t e1;
    int16_t e2;
    char e3[1];
};

struct _NET_BUFFER_LIST_POOL_PARAMETERS {
    struct _NDIS_OBJECT_HEADER e0;
    char e1;
    char e2;
    int16_t e3;
    int32_t e4;
    int32_t e5;
};

struct _OSVERSIONINFOW {
    int32_t e0;
    int32_t e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    int16_t e5[128];
};

struct _SEC_WINNT_AUTH_IDENTITY_W {
    int16_t * e0;
    int32_t e1;
    int16_t * e2;
    int32_t e3;
    int16_t * e4;
    int32_t e5;
    int32_t e6;
};

struct _SID_IDENTIFIER_AUTHORITY {
    char e0[6];
};

struct _SID {
    char e0;
    char e1;
    struct _SID_IDENTIFIER_AUTHORITY e2;
    int32_t e3[1];
};

struct _TYPEDEF_GUID {
    int32_t e0;
    int16_t e1;
    int16_t e2;
    char e3[8];
};

struct FWPM_CALLOUT0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    struct _TYPEDEF_GUID e5;
    int32_t e6;
};

struct FWPM_FILTER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    struct _TYPEDEF_GUID e5;
    struct _TYPEDEF_GUID e6;
    struct FWP_VALUE0_ e7;
    int32_t e8;
    struct FWPM_FILTER_CONDITION0_ * e9;
    struct FWPM_ACTION0_ e10;
    int64_t e11;
    struct _TYPEDEF_GUID * e12;
    int64_t e13;
    struct FWP_VALUE0_ e14;
};

struct FWPM_FILTER_CONDITION0_ {
    struct _TYPEDEF_GUID e0;
    int64_t e1;
    struct FWP_CONDITION_VALUE0_ e2;
};

struct FWPM_PROVIDER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct FWP_BYTE_BLOB_ e3;
    int16_t * e4;
};

struct FWPM_PROVIDER_CONTEXT1_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    int64_t e5;
    int64_t e6;
    int64_t e7;
};

struct FWPM_SESSION0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    struct _SID * e5;
    int16_t * e6;
    bool e7;
};

struct FWPM_SUBLAYER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    int16_t e5;
};

struct FWPS_CALLOUT1_ {
    struct _TYPEDEF_GUID e0;
    int32_t e1;
    void (*e2)(struct FWPS_INCOMING_VALUES0_ *, struct FWPS_INCOMING_METADATA_VALUES0_ *, int64_t *, int64_t *, struct FWPS_FILTER1_ *, int64_t, struct FWPS_CLASSIFY_OUT0_ *);
    int32_t (*e3)(int64_t, struct _TYPEDEF_GUID *, struct FWPS_FILTER1_ *);
    void (*e4)(int16_t, int32_t, int64_t);
};

struct _TYPEDEF_SCOPE_ID__PSCOPE_ID {
    int64_t e0;
};

struct FWPS_INCOMING_METADATA_VALUES0_ {
    int32_t e0;
    int32_t e1;
    int64_t e2;
    struct FWPS_DISCARD_METADATA0_ e3;
    int64_t e4;
    int32_t e5;
    int32_t e6;
    struct FWP_BYTE_BLOB_ * e7;
    int64_t e8;
    int64_t e9;
    int32_t e10;
    int32_t e11;
    int32_t e12;
    struct FWPS_INBOUND_FRAGMENT_METADATA0_ e13;
    int32_t e14;
    int64_t * e15;
    int64_t e16;
    struct _TYPEDEF_SCOPE_ID__PSCOPE_ID e17;
    struct _WSACMSGHDR * e18;
    int32_t e19;
    int64_t e20;
    int64_t * e21;
    int32_t e22;
    struct _IP_ADDRESS_PREFIX e23;
    int16_t e24;
    int64_t e25;
    int32_t e26;
    int32_t e27;
    struct sockaddr * e28;
    int64_t * e29;
    int32_t e30;
    int32_t e31;
    int32_t e32;
    int32_t e33;
    int32_t e34;
    int16_t e35;
    int32_t e36;
    int64_t * e37;
    int64_t * e38;
    int64_t e39;
};

struct FWPS_TRANSPORT_SEND_PARAMS0_ {
    char * e0;
    struct _TYPEDEF_SCOPE_ID__PSCOPE_ID e1;
    int64_t * e2;
    int32_t e3;
};

struct _UNICODE_STRING {
    int16_t e0;
    int16_t e1;
    int16_t * e2;
};

struct _WSACMSGHDR {
    int32_t e0;
    int32_t e1;
    int32_t e2;
};

struct sockaddr {
    int16_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(int64_t a1, int64_t a2);
/* Extracted from ProxifierDrv.sys (RetDec). WFP hooks subset. */

int64_t function_140001804(char * a1, int64_t a2, int64_t a3, int32_t a4) {
    int64_t v1 = (int64_t)a1;
    int64_t v2 = a2 & -256 | 2; // 0x140001844
    int64_t v3 = *(int64_t *)((int64_t)g14 + 64); // 0x140001851
    function_140001c80(v3, v2, 1, a4 != 1 ? 14 : 13, (int64_t)&g2, v1);
    int64_t v4 = 15; // 0x140001875
    if (g35 < 1011) {
        int64_t v5 = v1; // 0x1400018a4
        int64_t v6 = 1; // 0x1400018a4
        int64_t v7; // 0x140001804
        if ((char)v7 == 0) {
          lab_0x1400018c2:;
            int64_t v8 = 0x100000000 * v6 >> 32; // 0x1400018ce
            int64_t v9 = v8 + 304; // 0x1400018d1
            int64_t * v10 = ExAllocatePoolWithTag((int64_t)g42, (int32_t)v9, 0x746e7645); // 0x1400018d8
            int64_t v11 = (int64_t)v10; // 0x1400018d8
            int64_t result; // 0x140001804
            if (v10 != NULL) {
                // 0x140001918
                function_140005d00(v11, 0, 304);
                *(int32_t *)v10 = 304;
                *(int32_t *)(v11 + 24) = (int32_t)v6;
                *(int32_t *)(v11 + 32) = 1;
                *(int64_t *)(v11 + 216) = a2 & 0xffffffff;
                *(int64_t *)(v11 + 224) = a3;
                *(int32_t *)(v11 + 232) = a4;
                function_1400059c0(v11 + 304, v1, v8, (int64_t)&g80);
                result = function_14000129c(v11, 0);
            } else {
                int64_t v12 = *(int64_t *)((int64_t)g14 + 64); // 0x140001902
                int64_t v13 = function_14000199c(v12, v9 & -256 | 2, 1, v11 + 17 & 0xffffffff, (int64_t)&g2); // 0x140001906
                result = v13;
            }
            // 0x140001968
            return result;
        }
        int64_t v14 = 2;
        v4 = 16;
        while ((int32_t)v14 <= 0xf423f) {
            // 0x1400018b7
            v5++;
            v6 = v14;
            if (*(char *)v5 == 0) {
                goto lab_0x1400018c2;
            }
            v14 = v14 + 1 & 0xffffffff;
            v4 = 16;
        }
    }
    int64_t v15 = *(int64_t *)((int64_t)g14 + 64); // 0x140001890
    // 0x140001968
    return function_140001a64(v15, v2, 1, v4, (int64_t)&g2);
}

// Address range: 0x140001988 - 0x140001990
int64_t function_140001988(char * a1, int64_t a2, int32_t a3, int64_t a4) {
    // 0x140001988
    return function_140001804(a1, a2, (int64_t)a3, 0);
}

// Address range: 0x140001990 - 0x14000199b
int64_t function_14000199c(int64_t a1, uint64_t a2, uint64_t a3, int64_t a4, int64_t a5) {
    uint64_t v1 = a3 / 0x10000 % 0x10000; // 0x1400019c1
    uint64_t v2 = a3 + 0xffffffff; // 0x1400019c8
    int64_t v3 = g14; // 0x1400019e5
    int32_t v4 = *(int32_t *)(4 * (v2 / 32 % 2048 + 20 * v1) + 44 + v3); // 0x1400019ec
    if ((v4 & 1 << (int32_t)v2 % 32) == 0) {
        // 0x140001a2a
        return WppAutoLogTrace(a1, a2 % 256, a3 & 0xffffffff, a5, 0x1000000000000 * a4 >> 48, 0);
    }
    // 0x1400019f6
    if (*(char *)(80 * v1 + 41 + v3) >= (char)a2) {
        // 0x140001a04
        function_1400059a0();
    }
    // 0x140001a2a
    return WppAutoLogTrace(a1, a2 % 256, a3 & 0xffffffff, a5, 0x1000000000000 * a4 >> 48, 0);
}

// Address range: 0x140001a64 - 0x140001b59
int64_t function_140001a64(int64_t a1, uint64_t a2, uint64_t a3, int64_t a4, int64_t a5) {
    uint64_t v1 = a3 / 0x10000 % 0x10000; // 0x140001a89
    uint64_t v2 = a3 + 0xffffffff; // 0x140001a90
    int64_t v3 = g14; // 0x140001ab4
    int32_t v4 = *(int32_t *)(4 * (v2 / 32 % 2048 + 20 * v1) + 44 + v3); // 0x140001abb
    int64_t v5; // bp+48, 0x140001a64
    int64_t result; // 0x140001b3b
    if ((v4 & 1 << (int32_t)v2 % 32) == 0) {
        // 0x140001b0c
        result = WppAutoLogTrace(a1, a2 % 256, a3 & 0xffffffff, a5, 0x1000000000000 * a4 >> 48, (int64_t)&v5);
        return result;
    }
    // 0x140001ac5
    if (*(char *)(80 * v1 + 41 + v3) >= (char)a2) {
        // 0x140001ad3
        function_1400059a0();
    }
    // 0x140001b0c
    result = WppAutoLogTrace(a1, a2 % 256, a3 & 0xffffffff, a5, 0x1000000000000 * a4 >> 48, (int64_t)&v5);
    return result;
}

// Address range: 0x140001b5c - 0x140001c7e
int64_t function_140001b5c(int64_t a1, uint64_t a2, uint64_t a3, int64_t a4, int64_t a5) {
    uint64_t v1 = a3 / 0x10000 % 0x10000; // 0x140001b81
    uint64_t v2 = a3 + 0xffffffff; // 0x140001b88
    int64_t v3 = g14; // 0x140001bac
    int32_t v4 = *(int32_t *)(4 * (v2 / 32 % 2048 + 20 * v1) + 44 + v3); // 0x140001bb3
    int64_t v5; // bp+48, 0x140001b5c
    int64_t result; // 0x140001c5f
    if ((v4 & 1 << (int32_t)v2 % 32) == 0) {
        // 0x140001c1a
        result = WppAutoLogTrace(a1, a2 % 256, a3 & 0xffffffff, a5, 0x1000000000000 * a4 >> 48, (int64_t)&v5);
        return result;
    }
    // 0x140001bbd
    if (*(char *)(80 * v1 + 41 + v3) >= (char)a2) {
        // 0x140001bcb
        function_1400059a0();
    }
    // 0x140001c1a
    result = WppAutoLogTrace(a1, a2 % 256, a3 & 0xffffffff, a5, 0x1000000000000 * a4 >> 48, (int64_t)&v5);
    return result;
}

// Address range: 0x140001c80 - 0x140001e29
int64_t function_140001c80(int64_t a1, uint64_t a2, uint64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    int64_t v1 = g14; // 0x140001ca0
    uint64_t v2 = a3 / 0x10000 % 0x10000; // 0x140001cc3
    uint64_t v3 = a3 + 0xffffffff; // 0x140001cc7
    int32_t v4 = *(int32_t *)(4 * (v3 / 32 % 2048 + 20 * v2) + 44 + v1); // 0x140001cea
    if ((v4 & 1 << (int32_t)v3 % 32) != 0) {
        // 0x140001cf8
        if (*(char *)(80 * v2 + 41 + v1) >= (char)a2) {
            // 0x140001d0a
            if (a6 != 0) {
                int64_t v5 = 0; // 0x140001d12
                int64_t v6 = v5; // 0x140001d19
                while (*(char *)(v5 + a6) != 0) {
                    // 0x140001d12
                    v5 = v6 + 1;
                    v6 = v5;
                }
            }
            // 0x140001d25
            function_1400059a0();
        }
    }
    int64_t v7 = -1; // 0x140001d99
    int64_t v8; // 0x140001dc8
    if (a6 == 0) {
        // 0x140001dae
        v8 = a6 != 0 ? a6 : (int64_t)"NULL";
        return WppAutoLogTrace(a1, a2 % 256, a3 & 0xffffffff, a5, 0x1000000000000 * a4 >> 48, v8);
    }
    v7++;
    while (*(char *)(v7 + a6) != 0) {
        // 0x140001d9b
        v7++;
    }
    // 0x140001dae
    v8 = a6 != 0 ? a6 : (int64_t)"NULL";
    return WppAutoLogTrace(a1, a2 % 256, a3 & 0xffffffff, a5, 0x1000000000000 * a4 >> 48, v8);
}

// Address range: 0x140001e2c - 0x140001ed8
int64_t function_140005937(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x140005937
    return WppAutoLogTrace(a1, a2, a3, a4, a5, a6);
}

// Address range: 0x14000593d - 0x140005943
int64_t function_14000593d(int64_t a1, int64_t a2, int64_t a3) {
    // 0x14000593d
    return WppAutoLogStart(a1, a2, a3);
}

// Address range: 0x140005943 - 0x140005949
int64_t function_140005943(int64_t a1, int64_t a2) {
    // 0x140005943
    return WppAutoLogStop(a1, a2);
}

// Address range: 0x140005950 - 0x140005956
