//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int128_t;

// ------------------------ Structures ------------------------

struct FWPM_ACTION0_ {
    int32_t e0;
    int64_t e1;
};

struct FWPM_DISPLAY_DATA0_ {
    int16_t * e0;
    int16_t * e1;
};

struct FWPS_ACTION0_ {
    int32_t e0;
    int32_t e1;
};

struct FWPS_CLASSIFY_OUT0_ {
    int32_t e0;
    int64_t e1;
    int64_t e2;
    int32_t e3;
    int32_t e4;
    int32_t e5;
};

struct FWPS_DISCARD_METADATA0_ {
    int64_t e0;
    int32_t e1;
    int64_t e2;
};

struct FWPS_INBOUND_FRAGMENT_METADATA0_ {
    int32_t e0;
    int16_t e1;
    int32_t e2;
};

struct FWPS_INCOMING_VALUES0_ {
    int16_t e0;
    int32_t e1;
    struct FWPS_INCOMING_VALUE0_ * e2;
};

struct FWP_BYTE_BLOB_ {
    int32_t e0;
    char * e1;
};

struct FWP_CONDITION_VALUE0_ {
    int64_t e0;
    int64_t e1;
};

struct FWPS_FILTER_CONDITION0_ {
    int16_t e0;
    int16_t e1;
    int64_t e2;
    struct FWP_CONDITION_VALUE0_ e3;
};

struct FWP_VALUE0_ {
    int64_t e0;
    int64_t e1;
};

struct FWPS_FILTER1_ {
    int64_t e0;
    struct FWP_VALUE0_ e1;
    int16_t e2;
    int16_t e3;
    int32_t e4;
    struct FWPS_FILTER_CONDITION0_ * e5;
    struct FWPS_ACTION0_ e6;
    int64_t e7;
    struct FWPM_PROVIDER_CONTEXT1_ * e8;
};

struct FWPS_INCOMING_VALUE0_ {
    struct FWP_VALUE0_ e0;
};

struct _EPROCESS {
    int32_t e0;
};

struct _IP_ADDRESS_PREFIX {
    int64_t e0;
    char e1;
};

struct _KSPIN_LOCK_QUEUE {
    struct _KSPIN_LOCK_QUEUE * e0;
    int32_t * e1;
};

struct _KLOCK_QUEUE_HANDLE {
    struct _KSPIN_LOCK_QUEUE e0;
    char e1;
};

struct _KSPIN_LOCK_QUEUE {
    struct _KSPIN_LOCK_QUEUE * e0;
    int32_t * e1;
};

struct _LARGE_INTEGER {
    int64_t e0;
};

struct _MDL {
    struct _MDL * e0;
    int16_t e1;
    int16_t e2;
    int16_t e3;
    int16_t e4;
    struct _EPROCESS * e5;
    int64_t * e6;
    int64_t * e7;
    int32_t e8;
    int32_t e9;
};

struct _NDIS_OBJECT_HEADER {
    char e0;
    char e1;
    int16_t e2;
};

struct _NDIS_GENERIC_OBJECT {
    struct _NDIS_OBJECT_HEADER e0;
    int64_t * e1;
    int64_t * e2;
    int64_t e3;
};

struct _NET_BUFFER {
    int64_t e0;
    int16_t e1;
    int16_t e2;
    int64_t * e3;
    int64_t * e4[2];
    int64_t * e5[6];
    int64_t * e6[4];
    struct _LARGE_INTEGER e7;
    int64_t e8;
};

struct _NET_BUFFER_LIST {
    int64_t e0;
    struct _NET_BUFFER_LIST_CONTEXT * e1;
    struct _NET_BUFFER_LIST * e2;
    int64_t * e3;
    int64_t * e4[2];
    int64_t * e5[4];
    int64_t * e6[2];
    int64_t * e7;
    int64_t * e8;
    int32_t e9;
    int32_t e10;
    int32_t e11;
    int64_t e12;
    int64_t * e13[1];
};

struct _NET_BUFFER_LIST_CONTEXT {
    int64_t e0;
    int16_t e1;
    int16_t e2;
    char e3[1];
};

struct _NET_BUFFER_LIST_POOL_PARAMETERS {
    struct _NDIS_OBJECT_HEADER e0;
    char e1;
    char e2;
    int16_t e3;
    int32_t e4;
    int32_t e5;
};

struct _OSVERSIONINFOW {
    int32_t e0;
    int32_t e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    int16_t e5[128];
};

struct _SEC_WINNT_AUTH_IDENTITY_W {
    int16_t * e0;
    int32_t e1;
    int16_t * e2;
    int32_t e3;
    int16_t * e4;
    int32_t e5;
    int32_t e6;
};

struct _SID_IDENTIFIER_AUTHORITY {
    char e0[6];
};

struct _SID {
    char e0;
    char e1;
    struct _SID_IDENTIFIER_AUTHORITY e2;
    int32_t e3[1];
};

struct _TYPEDEF_GUID {
    int32_t e0;
    int16_t e1;
    int16_t e2;
    char e3[8];
};

struct FWPM_CALLOUT0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    struct _TYPEDEF_GUID e5;
    int32_t e6;
};

struct FWPM_FILTER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    struct _TYPEDEF_GUID e5;
    struct _TYPEDEF_GUID e6;
    struct FWP_VALUE0_ e7;
    int32_t e8;
    struct FWPM_FILTER_CONDITION0_ * e9;
    struct FWPM_ACTION0_ e10;
    int64_t e11;
    struct _TYPEDEF_GUID * e12;
    int64_t e13;
    struct FWP_VALUE0_ e14;
};

struct FWPM_FILTER_CONDITION0_ {
    struct _TYPEDEF_GUID e0;
    int64_t e1;
    struct FWP_CONDITION_VALUE0_ e2;
};

struct FWPM_PROVIDER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct FWP_BYTE_BLOB_ e3;
    int16_t * e4;
};

struct FWPM_PROVIDER_CONTEXT1_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    int64_t e5;
    int64_t e6;
    int64_t e7;
};

struct FWPM_SESSION0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    struct _SID * e5;
    int16_t * e6;
    bool e7;
};

struct FWPM_SUBLAYER0_ {
    struct _TYPEDEF_GUID e0;
    struct FWPM_DISPLAY_DATA0_ e1;
    int32_t e2;
    struct _TYPEDEF_GUID * e3;
    struct FWP_BYTE_BLOB_ e4;
    int16_t e5;
};

struct FWPS_CALLOUT1_ {
    struct _TYPEDEF_GUID e0;
    int32_t e1;
    void (*e2)(struct FWPS_INCOMING_VALUES0_ *, struct FWPS_INCOMING_METADATA_VALUES0_ *, int64_t *, int64_t *, struct FWPS_FILTER1_ *, int64_t, struct FWPS_CLASSIFY_OUT0_ *);
    int32_t (*e3)(int64_t, struct _TYPEDEF_GUID *, struct FWPS_FILTER1_ *);
    void (*e4)(int16_t, int32_t, int64_t);
};

struct _TYPEDEF_SCOPE_ID__PSCOPE_ID {
    int64_t e0;
};

struct FWPS_INCOMING_METADATA_VALUES0_ {
    int32_t e0;
    int32_t e1;
    int64_t e2;
    struct FWPS_DISCARD_METADATA0_ e3;
    int64_t e4;
    int32_t e5;
    int32_t e6;
    struct FWP_BYTE_BLOB_ * e7;
    int64_t e8;
    int64_t e9;
    int32_t e10;
    int32_t e11;
    int32_t e12;
    struct FWPS_INBOUND_FRAGMENT_METADATA0_ e13;
    int32_t e14;
    int64_t * e15;
    int64_t e16;
    struct _TYPEDEF_SCOPE_ID__PSCOPE_ID e17;
    struct _WSACMSGHDR * e18;
    int32_t e19;
    int64_t e20;
    int64_t * e21;
    int32_t e22;
    struct _IP_ADDRESS_PREFIX e23;
    int16_t e24;
    int64_t e25;
    int32_t e26;
    int32_t e27;
    struct sockaddr * e28;
    int64_t * e29;
    int32_t e30;
    int32_t e31;
    int32_t e32;
    int32_t e33;
    int32_t e34;
    int16_t e35;
    int32_t e36;
    int64_t * e37;
    int64_t * e38;
    int64_t e39;
};

struct FWPS_TRANSPORT_SEND_PARAMS0_ {
    char * e0;
    struct _TYPEDEF_SCOPE_ID__PSCOPE_ID e1;
    int64_t * e2;
    int32_t e3;
};

struct _UNICODE_STRING {
    int16_t e0;
    int16_t e1;
    int16_t * e2;
};

struct _WSACMSGHDR {
    int32_t e0;
    int32_t e1;
    int32_t e2;
};

struct sockaddr {
    int16_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(int64_t a1, int64_t a2);
/* Additional WFP-related functions. */

int64_t function_140002748(int32_t a1, int64_t a2, int64_t a3, int64_t a4) {
    int64_t v1 = *(int64_t *)((int64_t)g14 + 64); // 0x140002787
    function_14000199c(v1, a2 & -256 | 5, 1, 10, (int64_t)&g5);
    char v2 = a3; // 0x140002794
    int64_t v3; // 0x140002748
    int32_t v4; // 0x140002748
    int32_t v5; // 0x1400027d9
    int16_t v6; // 0x1400027d2
    if (v2 != 17) {
        if (v2 != 6) {
            // 0x14000282d
            v4 = (int32_t)a3 % 256;
            v3 = (int64_t)"41:NfeCreateFlow: unkown IP protocol";
            goto lab_0x140002838;
        } else {
            // 0x1400027c0
            v6 = (char)a4 == 0 ? 20 : 22;
            v5 = (char)a4 != 0 ? g59 : g58;
            goto lab_0x1400027e0;
        }
    } else {
        // 0x140002799
        v6 = (char)a4 == 0 ? 24 : 26;
        v5 = (char)a4 != 0 ? g57 : g56;
        goto lab_0x1400027e0;
    }
  lab_0x1400027e0:;
    int64_t * v7 = ExAllocatePoolWithTag((int64_t)g42, 72, 0x776f6c46); // 0x1400027f1
    v4 = 0;
    v3 = (int64_t)"48:ExAllocatePoolWithTag failed";
    if (v7 == NULL) {
        goto lab_0x140002838;
      lab_0x140002838:
        // 0x140002838
        function_140001988((char *)v3, 0xc0000001, v4, 10);
        // 0x140002844
        return 0;
    }
    int64_t result = (int64_t)v7; // 0x1400027f1
    function_140005d00(result, 0, 72);
    *(int32_t *)(result + 32) = a1;
    *(int64_t *)(result + 40) = a2;
    *(int16_t *)(result + 24) = v6;
    *(int32_t *)(result + 28) = v5;
    // 0x140002844
    return result;
}

// Address range: 0x140002860 - 0x14000290d
int64_t function_14000291c(void) {
    int64_t v1 = 0; // 0x140002943
    int64_t result; // 0x14000291c
    int64_t v2; // bp-56, 0x14000291c
    while (true) {
        // 0x140002946
        result = v1;
        KeAcquireInStackQueuedSpinLock((int32_t *)&g78, (struct _KLOCK_QUEUE_HANDLE *)&v2);
        if (g44 == (int128_t *)&g44) {
            // break (via goto) -> 0x1400029a4
            goto lab_0x1400029a4;
        }
        int64_t v3 = (int64_t)g44; // 0x140002965
        if (*(int64_t *)(v3 + 8) != (int64_t)&g44) {
            // 0x1400029e5
            __asm_int(41);
            return result;
        }
        int64_t v4 = *(int64_t *)g44; // 0x140002977
        int64_t * v5 = (int64_t *)(v4 + 8); // 0x14000297a
        if (*v5 != v3) {
            // 0x1400029e5
            __asm_int(41);
            return result;
        }
        // 0x1400029b4
        g44 = (int128_t *)v4;
        *v5 = (int64_t)&g44;
        g46--;
        int64_t v6 = *(int64_t *)(v3 + 16); // 0x140002994
        *(char *)(v3 + 65) = 0;
        KeReleaseInStackQueuedSpinLock((struct _KLOCK_QUEUE_HANDLE *)&v2);
        int32_t v7 = FwpsFlowRemoveContext0(v6, *(int16_t *)(v3 + 24), *(int32_t *)(v3 + 28)); // 0x1400029be
        while (v7 >= 0) {
            // 0x140002946
            KeAcquireInStackQueuedSpinLock((int32_t *)&g78, (struct _KLOCK_QUEUE_HANDLE *)&v2);
            if (g44 == (int128_t *)&g44) {
                // break (via goto) -> 0x1400029a4
                goto lab_0x1400029a4;
            }
            // 0x140002971
            v3 = (int64_t)g44;
            if (*(int64_t *)(v3 + 8) != (int64_t)&g44) {
                // 0x1400029e5
                __asm_int(41);
                return result;
            }
            // 0x140002977
            v4 = *(int64_t *)g44;
            v5 = (int64_t *)(v4 + 8);
            if (*v5 != v3) {
                // 0x1400029e5
                __asm_int(41);
                return result;
            }
            // 0x1400029b4
            g44 = (int128_t *)v4;
            *v5 = (int64_t)&g44;
            g46--;
            v6 = *(int64_t *)(v3 + 16);
            *(char *)(v3 + 65) = 0;
            KeReleaseInStackQueuedSpinLock((struct _KLOCK_QUEUE_HANDLE *)&v2);
            v7 = FwpsFlowRemoveContext0(v6, *(int16_t *)(v3 + 24), *(int32_t *)(v3 + 28));
        }
        // 0x1400029cd
        v1 = v7;
        int64_t v8; // 0x14000291c
        function_140001988("162:FwpsFlowRemoveContext0 failed", v1, (int32_t)v6, v8);
    }
  lab_0x1400029a4:
    // 0x1400029a4
    KeReleaseInStackQueuedSpinLock((struct _KLOCK_QUEUE_HANDLE *)&v2);
  lab_0x1400029ec:
    // 0x1400029ec
    return result;
}

// Address range: 0x140002a10 - 0x140002a17
int32_t function_1400054df(int64_t * poolHandle, int16_t contextSize, int16_t contextBackFill, struct _MDL * mdlChain, int32_t dataOffset, int32_t dataLength, struct _NET_BUFFER_LIST ** netBufferList) {
    // 0x1400054df
    return FwpsAllocateNetBufferAndNetBufferList0(poolHandle, contextSize, contextBackFill, mdlChain, dataOffset, dataLength, netBufferList);
}

// Address range: 0x1400054e5 - 0x1400054eb
void function_1400054e5(struct _NET_BUFFER_LIST * netBufferList) {
    // 0x1400054e5
    FwpsFreeNetBufferList0(netBufferList);
}

// Address range: 0x1400054eb - 0x1400054f1
int32_t function_1400054eb(int64_t * injectionHandle, int64_t * injectionContext, int64_t endpointHandle, int32_t flags, struct FWPS_TRANSPORT_SEND_PARAMS0_ * sendArgs, int16_t addressFamily, int64_t compartmentId, struct _NET_BUFFER_LIST * netBufferList, void (*completionFn)(int64_t *, struct _NET_BUFFER_LIST *, char), int64_t * completionContext) {
    // 0x1400054eb
    return FwpsInjectTransportSendAsync0(injectionHandle, injectionContext, endpointHandle, flags, sendArgs, addressFamily, compartmentId, netBufferList, completionFn, completionContext);
}

// Address range: 0x1400054f1 - 0x1400054f7
int32_t function_1400054f1(int64_t * injectionHandle, int64_t * injectionContext, int64_t * reserved, int32_t flags, int16_t addressFamily, int64_t compartmentId, int32_t interfaceIndex, int32_t subInterfaceIndex, struct _NET_BUFFER_LIST * netBufferList, void (*completionFn)(int64_t *, struct _NET_BUFFER_LIST *, char), int64_t * completionContext) {
    // 0x1400054f1
    return FwpsInjectTransportReceiveAsync0(injectionHandle, injectionContext, reserved, flags, addressFamily, compartmentId, interfaceIndex, subInterfaceIndex, netBufferList, completionFn, completionContext);
}

// Address range: 0x1400054f7 - 0x1400054fd
int64_t function_1400054f7(int64_t * injectionHandle, struct _NET_BUFFER_LIST * netBufferList, int64_t ** injectionContext) {
    // 0x1400054f7
    return FwpsQueryPacketInjectionState0(injectionHandle, netBufferList, injectionContext);
}

// Address range: 0x1400054fd - 0x140005503
int32_t function_1400054fd(int64_t flowId, int16_t layerId, int32_t calloutId, int64_t flowContext) {
    // 0x1400054fd
    return FwpsFlowAssociateContext0(flowId, layerId, calloutId, flowContext);
}

// Address range: 0x140005503 - 0x140005509
int32_t function_140005503(int64_t flowId, int16_t layerId, int32_t calloutId) {
    // 0x140005503
    return FwpsFlowRemoveContext0(flowId, layerId, calloutId);
}

// Address range: 0x140005509 - 0x14000550f
int32_t function_140005509(int64_t * classifyContext, int32_t flags, int64_t * classifyHandle) {
    // 0x140005509
    return FwpsAcquireClassifyHandle0(classifyContext, flags, classifyHandle);
}

// Address range: 0x14000550f - 0x140005515
void function_14000550f(int64_t classifyHandle) {
    // 0x14000550f
    FwpsReleaseClassifyHandle0(classifyHandle);
}

// Address range: 0x140005515 - 0x14000551b
int32_t function_140005515(int64_t classifyHandle, int64_t filterId, int32_t flags, struct FWPS_CLASSIFY_OUT0_ * classifyOut) {
    // 0x140005515
    return FwpsPendClassify0(classifyHandle, filterId, flags, classifyOut);
}

// Address range: 0x14000551b - 0x140005521
void function_14000551b(int64_t classifyHandle, int32_t flags, struct FWPS_CLASSIFY_OUT0_ * classifyOut) {
    // 0x14000551b
    FwpsCompleteClassify0(classifyHandle, flags, classifyOut);
}

// Address range: 0x140005521 - 0x140005527
int32_t function_140005521(int64_t classifyHandle, int64_t filterId, int32_t flags, int64_t ** writableLayerData, struct FWPS_CLASSIFY_OUT0_ * classifyOut) {
    // 0x140005521
    return FwpsAcquireWritableLayerDataPointer0(classifyHandle, filterId, flags, writableLayerData, classifyOut);
}

// Address range: 0x140005527 - 0x14000552d
void function_140005527(int64_t classifyHandle, int64_t * modifiedLayerData, int32_t flags) {
    // 0x140005527
    FwpsApplyModifiedLayerData0(classifyHandle, modifiedLayerData, flags);
}

// Address range: 0x14000552d - 0x140005533
int64_t function_14000552d(int64_t * redirectRecords, int64_t * redirectHandle, int64_t ** redirectContext) {
    // 0x14000552d
    return FwpsQueryConnectionRedirectState0(redirectRecords, redirectHandle, redirectContext);
}

// Address range: 0x140005533 - 0x140005539
int32_t function_140005533(int64_t * deviceObject, struct FWPS_CALLOUT1_ * callout, int32_t * calloutId) {
    // 0x140005533
    return FwpsCalloutRegister1(deviceObject, callout, calloutId);
}

// Address range: 0x140005539 - 0x14000553f
int32_t function_140005539(struct _TYPEDEF_GUID * calloutKey) {
    // 0x140005539
    return FwpsCalloutUnregisterByKey0(calloutKey);
}

// Address range: 0x14000553f - 0x140005545
int32_t function_14000553f(int16_t addressFamily, int32_t flags, int64_t ** injectionHandle) {
    // 0x14000553f
    return FwpsInjectionHandleCreate0(addressFamily, flags, injectionHandle);
}

// Address range: 0x140005545 - 0x14000554b
int32_t function_140005545(int64_t * injectionHandle) {
    // 0x140005545
    return FwpsInjectionHandleDestroy0(injectionHandle);
}

// Address range: 0x14000554b - 0x140005551
int32_t function_14000554b(struct _TYPEDEF_GUID * providerGuid, int32_t flags, int64_t ** redirectHandle) {
    // 0x14000554b
    return FwpsRedirectHandleCreate0(providerGuid, flags, redirectHandle);
}

// Address range: 0x140005551 - 0x140005557
void function_140005551(int64_t * redirectHandle) {
    // 0x140005551
    FwpsRedirectHandleDestroy0(redirectHandle);
}

// Address range: 0x140005557 - 0x14000555d
int32_t function_140005557(int16_t * serverName, int32_t authnService, struct _SEC_WINNT_AUTH_IDENTITY_W * authIdentity, struct FWPM_SESSION0_ * session, int64_t ** engineHandle) {
    // 0x140005557
    return FwpmEngineOpen0(serverName, authnService, authIdentity, session, engineHandle);
}

// Address range: 0x14000555d - 0x140005563
int32_t function_14000555d(int64_t * engineHandle) {
    // 0x14000555d
    return FwpmEngineClose0(engineHandle);
}

// Address range: 0x140005563 - 0x140005569
int32_t function_140005563(int64_t * engineHandle, struct FWPM_PROVIDER0_ * provider, int64_t * sd) {
    // 0x140005563
    return FwpmProviderAdd0(engineHandle, provider, sd);
}

// Address range: 0x140005569 - 0x14000556f
int32_t function_140005569(int64_t * engineHandle, struct FWPM_SUBLAYER0_ * subLayer, int64_t * sd) {
    // 0x140005569
    return FwpmSubLayerAdd0(engineHandle, subLayer, sd);
}

// Address range: 0x14000556f - 0x140005575
int32_t function_14000556f(int64_t * engineHandle, struct FWPM_CALLOUT0_ * callout, int64_t * sd, int32_t * id) {
    // 0x14000556f
    return FwpmCalloutAdd0(engineHandle, callout, sd, id);
}

// Address range: 0x140005575 - 0x14000557b
int32_t function_140005575(int64_t * engineHandle, struct FWPM_FILTER0_ * filter, int64_t * sd, int64_t * id) {
    // 0x140005575
    return FwpmFilterAdd0(engineHandle, filter, sd, id);
}

// Address range: 0x14000557b - 0x140005581
